### ISSUE TITLE
Uncaught NullError: method not found: '$sub' on null

### ISSUE THREAD

**Issue by rayk** [dart-atom/dartlang#1003]
[Enter steps to reproduce below:]

1. ... In my main I have ``` Stream status = await harper.RegisterFor(Feed.status);```
2. ...  then the method
```
Future<Stream> RegisterFor(Feed type) async {
    return sc.stream;
  }
```
3. Getting rid of the Future and sync return a stream is find... But I planning to make a couple couple of calls before returning.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.19

### Stack Trace

Uncaught NullError: method not found: '$sub' on null

```
At /Users/rayk/.atom/packages/dartlang/web/entry.dart.js:26971

TypeError: Cannot read property '$sub' of undefined
    at [object Object].J.$sub$n (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:76413:40)
    at DebuggerView.dart.DebuggerView._jumpToLocation$2$addExecMarker (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:34237:120)
    at FlowControlSection__handleIsolateChange_closure.dart.FlowControlSection__handleIsolateChange_closure.call$1 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:34620:14)
    at _RootZone.dart._RootZone.runUnary$2 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:48662:20)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:46850:47)
    at [object Object].dart._Future.static._Future__propagateToListeners (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:46758:120)
    at _Future.dart._Future._completeWithValue$1 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:46617:11)
    at _Future__asyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:46835:20)
    at [object Object].dart._microtaskLoop (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:45664:27)
    at [object Object].dart._startMicrotaskLoop (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:45670:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:27351:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:29215:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:26962:25)
    at [object Object].dart._callInIsolate (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:26604:28)
    at dart.invokeClosure (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:28184:20)
    at /Users/rayk/.atom/packages/dartlang/web/entry.dart.js:28205:18
```

### Commands

```
     -1:26.6.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
  3x -1:20.2.0 core:move-down (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -1:19.5.0 dartlang:newline (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -1:19.5.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -1:16.3.0 dartlang:newline (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -1:16.3.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -1:15.6.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
  6x -1:13.4.0 core:move-up (atom-text-editor.editor.power-mode.is-focused)
     -1:02.2.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
     -0:37.3.0 dartlang:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:37.3.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:37 core:move-up (atom-text-editor.editor.power-mode.is-focused)
  2x -0:34.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:26.3.0 dartlang:newline (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:26.3.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:11.5.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "gpp-compiler",
      "language-c",
      "language-objective-c",
      "language-csharp",
      "symbols-view",
      "spell-check",
      "spell-check-test",
      "spell-check-project",
      "linter-scspell"
    ],
    "followSymlinks": false,
    "themes": [
      "one-dark-ui",
      "gruvbox-plus-syntax"
    ]
  },
  "dartlang": {
    "debuggerCaughtExceptions": "uncaught",
    "formatOnSave": true,
    "hoverTooltip": true,
    "isolateReload": true,
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
activate-power-mode, v0.5.2
atom-ctags, v4.5.2
atom-toolbar, v0.1.6
dartlang, v0.6.19
dash, v1.6.1
file-icons, v1.7.12
flutter, v0.2.2
gruvbox-plus-syntax, v1.2.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
linter, v1.11.4
linter-dartanalyzer, v0.3.2
pigments, v0.26.3
pretty-json, v1.4.0
project-manager, v2.9.7
rest-client, v1.1.0
synced-sidebar, v0.4.3
tablr, v1.3.1
tool-bar, v0.4.0
tool-bar-main, v0.0.9
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
I'm not able to repro, and from looking at the code, it's not immediately clear how we'd get here. Closing, but thanks for the report!
