### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get$onRunnablesChanged' of null

### ISSUE THREAD

**Issue by avoivo** [dart-atom/dartlang#1009]
I have just installed datlang plugin version 0.6.20 and every time a open atom it crashes.

**Atom Version**: 1.7.4
**System**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.20

### Stack Trace

Uncaught TypeError: Cannot read property 'get$onRunnablesChanged' of null

```
At C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:72723

TypeError: Cannot read property 'get$onRunnablesChanged' of null
    at DartToolbarContribution.dart.DartToolbarContribution._bindLaunchManager$3 (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:72723:93)
    at DartToolbarContribution.dart.DartToolbarContribution._buildLeftTile$0 (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:72668:14)
    at AtomDartPackage_closure0.dart.AtomDartPackage_closure0.call$1 (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:40027:60)
    at registerPackage__closure.dart.registerPackage__closure.call$1 (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:68202:25)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:27856:28)
    at dart._callDartFunction (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:59711:31)
    at Object.consumeToolbar (C:\Users\thanasis.voivodas\.atom\packages\dartlang\web\entry.dart.js:59997:20)
    at Provider.module.exports.Provider.provide (C:\Users\thanasis.voivodas\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\thanasis.voivodas\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "symbols-tree-view"
    ],
    "followSymlinks": false
  },
  "dartlang": {
    "configureErrorsView": "todos",
    "formatOnSave": true,
    "sdkLocation": "C:\\Program Files\\Dart\\dart-sdk",
    "sendUsage": false,
    "showErrorsView": false,
    "showOutlineView": false,
    "showTodos": true
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.20
file-icons, v1.7.12
flutter, v0.2.2
linter, v1.11.4
minimap, v4.24.2
synced-sidebar, v0.4.3
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report!

**Comment by devoncarew** [comment]
@avoivo, can you update to the latest published, restart atom, and confirm that the issue is fixed? Thanks!

**Comment by avoivo** [comment]
@devoncarew  i confirm that it works like a charm. :+1:
