### ISSUE TITLE
Uncaught Invalid argument: null

### ISSUE THREAD

**Issue by mezoni** [dart-atom/dartlang#1013]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.21

### Stack Trace

Uncaught Invalid argument: null

```
At /home/user/.atom/packages/dartlang/web/entry.dart.js:26712

Invalid argument: null
    at [object Object].dart.wrapException (/home/user/.atom/packages/dartlang/web/entry.dart.js:27786:17)
    at [object Object].dart.throwExpression (/home/user/.atom/packages/dartlang/web/entry.dart.js:27799:15)
    at JSString.dart.JSString.contains$2 (/home/user/.atom/packages/dartlang/web/entry.dart.js:26225:13)
    at JSString.dart.JSString.contains$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:26231:21)
    at ConsoleView.dart.ConsoleView.ConsoleView$2 (/home/user/.atom/packages/dartlang/web/entry.dart.js:33261:18)
    at [object Object].dart.ConsoleView.static.ConsoleView$ (/home/user/.atom/packages/dartlang/web/entry.dart.js:33280:14)
    at ConsoleController.dart.ConsoleController._launchAdded$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:32986:18)
    at [object Object].<anonymous> (/home/user/.atom/packages/dartlang/web/entry.dart.js:28034:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/user/.atom/packages/dartlang/web/entry.dart.js:48319:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:47570:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._async$_add$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:47520:16)
    at _SyncBroadcastStreamController__sendData_closure.dart._SyncBroadcastStreamController__sendData_closure.call$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:46113:22)
    at _SyncBroadcastStreamController.dart._BroadcastStreamController._forEachListener$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:46053:20)
    at _SyncBroadcastStreamController.dart._SyncBroadcastStreamController._sendData$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:46096:14)
    at LaunchManager.dart.LaunchManager.addLaunch$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:36433:12)
    at CliLaunchType.dart.CliLaunchType.performLaunch$2 (/home/user/.atom/packages/dartlang/web/entry.dart.js:37006:17)
    at RunApplicationManager.dart.RunApplicationManager.run$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:41809:22)
    at DartToolbarContribution.dart.DartToolbarContribution._handleRunLaunch$0 (/home/user/.atom/packages/dartlang/web/entry.dart.js:72773:87)
    at [object Object].<anonymous> (/home/user/.atom/packages/dartlang/web/entry.dart.js:28028:32)
    at CoreElement_click_closure.dart.CoreElement_click_closure.call$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:35542:21)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/user/.atom/packages/dartlang/web/entry.dart.js:48319:20)
    at _ForwardingStreamSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:47570:20)
    at _ForwardingStreamSubscription.dart._BufferingStreamSubscription._async$_add$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:47520:16)
    at _ForwardingStreamSubscription.dart._ForwardingStreamSubscription._async$_add$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:47946:14)
    at [object Object].J._async$_add$1$x (/home/user/.atom/packages/dartlang/web/entry.dart.js:76151:41)
    at _WhereStream.dart._WhereStream._handleData$2 (/home/user/.atom/packages/dartlang/web/entry.dart.js:48023:13)
    at _ForwardingStreamSubscription.dart._ForwardingStreamSubscription._handleData$1.H.computeSignature.T.func [as _handleData$1] (/home/user/.atom/packages/dartlang/web/entry.dart.js:47974:22)
    at [object Object].<anonymous> (/home/user/.atom/packages/dartlang/web/entry.dart.js:28034:32)
    at invokeClosure_closure0.dart.invokeClosure_closure0.call$0 (/home/user/.atom/packages/dartlang/web/entry.dart.js:28977:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:26703:25)
```

### Commands

```
  2x -0:28.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:08.0 core:delete (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:select-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  },
  "dartlang": {
    "debuggerCaughtExceptions": "uncaught",
    "formatOnSave": true,
    "hoverTooltip": true,
    "isolateReload": true,
    "sdkLocation": "/home/user/tools/dart/dart-sdk",
    "sendUsage": false,
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.21
linter, v1.11.4
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by mezoni** [comment]
Fixed but not by the better way.
I can see displayed some information which does not helps locate the problem (previously was an exception).
P.S.
But `Uncaught Invalid argument: null` fixed, I agree.
