### ISSUE TITLE
Uncaught [Analyzer RequestError method: execution.createContext, code: INVALID_PARAMETER, message...

### ISSUE THREAD

**Issue by mezoni** [dart-atom/dartlang#1016]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.22

### Stack Trace

Uncaught [Analyzer RequestError method: execution.createContext, code: INVALID_PARAMETER, message: Invalid parameter 'params.contextRoot'. Expected to be String.]

```
At /home/user/.atom/packages/dartlang/web/entry.dart.js:26680

[Analyzer RequestError method: execution.createContext, code: INVALID_PARAMETER, message: Invalid parameter 'params.contextRoot'. Expected to be String.]
    at [object Object].dart.wrapException (/home/user/.atom/packages/dartlang/web/entry.dart.js:27754:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/home/user/.atom/packages/dartlang/web/entry.dart.js:48249:19)
    at [object Object].dart._microtaskLoop (/home/user/.atom/packages/dartlang/web/entry.dart.js:45481:27)
    at [object Object].dart._startMicrotaskLoop (/home/user/.atom/packages/dartlang/web/entry.dart.js:45487:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/user/.atom/packages/dartlang/web/entry.dart.js:27060:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/user/.atom/packages/dartlang/web/entry.dart.js:28939:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/user/.atom/packages/dartlang/web/entry.dart.js:26671:25)
    at [object Object].dart._callInIsolate (/home/user/.atom/packages/dartlang/web/entry.dart.js:26313:28)
    at dart.invokeClosure (/home/user/.atom/packages/dartlang/web/entry.dart.js:27902:20)
    at /home/user/.atom/packages/dartlang/web/entry.dart.js:27923:18
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  },
  "dartlang": {
    "debuggerCaughtExceptions": "uncaught",
    "formatOnSave": true,
    "hoverTooltip": true,
    "isolateReload": true,
    "sdkLocation": "/home/user/tools/dart/dart-sdk",
    "sendUsage": false,
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.22
linter, v1.11.4
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by mezoni** [comment]
This related to this bug: https://github.com/dart-atom/dartlang/issues/1013
Because it was not fixed properly (but just a partially).
