### ISSUE TITLE
Uncaught Error: Cannot set property '_wasPauseAtStart' of undefined

### ISSUE THREAD

**Issue by tvolkert** [dart-atom/dartlang#1044]
1. Launch Flutter gallery

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.27

### Stack Trace

Uncaught Error: Cannot set property '_wasPauseAtStart' of undefined

```
At /Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:27055

TypeError: Cannot set property '_wasPauseAtStart' of undefined
    at ObservatoryConnection.dart.ObservatoryConnection._handleDebugEvent$1 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:38452:41)
    at [object Object].<anonymous> (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:28375:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:48848:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:48096:20)
    at _DelayedData.dart._DelayedData.perform$1 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:48241:18)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:48295:16)
    at [object Object].dart._microtaskLoop (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:46046:27)
    at [object Object].dart._startMicrotaskLoop (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:46052:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:27433:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:29312:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:27046:25)
    at [object Object].dart._callInIsolate (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:26688:28)
    at dart.invokeClosure (/Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:28275:20)
    at /Users/tvolkert/.atom/packages/dartlang/web/entry.dart.js:28296:18
```

### Commands

```
  2x -3:29 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-emacs-syntax.theme-native-ui)
     -0:26.8.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:26.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-emacs-syntax.theme-native-ui)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "themes": [
      "native-ui",
      "emacs-syntax"
    ]
  },
  "dartlang": {
    "sdkLocation": "/Users/tvolkert/project/flutter/flutter/bin/cache/dart-sdk",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.27
emacs-syntax, v0.2.0
flutter, v0.2.3
linter, v1.11.11
native-ui, v0.18.2
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by tvolkert** [comment]
@devoncarew
