### ISSUE TITLE
Uncaught TypeError: Cannot read property 'analyzing' of null

### ISSUE THREAD

**Issue by zanderso** [dart-atom/dartlang#106]
[Enter steps to reproduce below:]

1. Packages > Dart > Show Analysis Server Status
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.3.4

### Stack Trace

Uncaught TypeError: Cannot read property 'analyzing' of null

```
At /usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:117

TypeError: Cannot read property 'analyzing' of null
  at AnalysisServer.dart.AnalysisServer.get$isBusy (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:16655:28)
  at AnalysisServerDialog.dart.AnalysisServerDialog._updateStatus$0 (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:17281:67)
  at AnalysisServerDialog.dart.AnalysisServerDialog.showDialog$0 (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:17267:14)
  at AnalysisServerDialog_closure.dart.AnalysisServerDialog_closure.call$1 (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:17325:62)
  at CommandRegistry_add_closure.dart.CommandRegistry_add_closure.call$1 (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:16284:48)
  at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:13602:28)
  at dart._callDartFunction (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:28761:31)
  at atom-workspace.<anonymous> (/usr/local/google/home/zra/.atom/packages/dartlang/web/entry.dart.js:28749:18)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:18.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.4.0 dartlang:analysis-server-status (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "dartlang": {
    "sdkLocation": "/usr/local/google/home/zra/mojo/src/third_party/dart-sdk/dart-sdk"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.3.4

# Dev
No dev packages
```

**Comment by zanderso** [comment]
I did not have the 'linter' package installed. A better failure mode here might be helpful.
