### ISSUE TITLE
Cannot create breakpoints

### ISSUE THREAD

**Issue by KOGI** [dart-atom/dartlang#1093]
I am unable to create breakpoints anywhere in my code. Every time, I'm greeted with "Uncaught Error: Cannot decorate a destroyed marker".

Here's the stack trace:

[Enter steps to reproduce below:]

1. Open dart project in Atom
2. Open any `.dart` file
3. Click in the gutter to add a breakpoint (or press F9)

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.40

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:28377

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\Bob\AppData\Local\atom\app-1.11.1\resources\app.asar\src\decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\Bob\AppData\Local\atom\app-1.11.1\resources\app.asar\src\text-editor.js:1657:37)
    at JsObject.dart.JsObject.callMethod$2 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:46228:44)
    at TextEditor.dart.ProxyHolder.invoke$4 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:49146:27)
    at TextEditor.dart.ProxyHolder.invoke$3 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:49162:21)
    at TextEditor.dart.TextEditor.decorateMarker$2 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:48998:46)
    at _EditorBreakpoint.dart._EditorBreakpoint._EditorBreakpoint$4 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:56379:21)
    at undefined.dart._EditorBreakpoint.static._EditorBreakpoint$ (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:56386:14)
    at BreakpointManager.dart.BreakpointManager._createEditorBreakpoint$2 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:56087:40)
    at BreakpointManager.dart.BreakpointManager.addBreakpoint$1 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:56010:18)
    at BreakpointManager.dart.BreakpointManager._toggleLineNumberBreakpoint$2 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:56127:16)
    at _GutterTracker__initLineNumberGutter_closure.dart._GutterTracker__initLineNumberGutter_closure.call$1 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:56353:32)
    at invokeClosure_closure0.dart.invokeClosure_closure0.call$0 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:30638:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:28368:25)
    at undefined.dart._callInIsolate (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:28008:28)
    at dart.invokeClosure (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:29596:20)
    at HTMLDivElement.<anonymous> (C:\Users\Bob\.atom\packages\dartlang\web\entry.dart.js:29615:18)
```

### Commands

```
     -5:40 core:save (atom-text-editor.editor.is-focused)
     -5:38.6.0 core:close (atom-text-editor.editor.is-focused)
  4x -5:38.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-skittles.theme-atom-dark-ui)
     -3:06.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:04.8.0 core:copy (atom-text-editor.editor.is-focused)
     -3:02.3.0 tree-view:remove (span.name.icon.icon-file-text)
  3x -3:00.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-skittles.theme-atom-dark-ui)
     -1:28.9.0 dartlang:debug-run (atom-text-editor.editor.is-focused)
     -0:34.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:31.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:31.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:30.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:29.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:26.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:26.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.3.0 dartlang:analysis-server-status (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "build",
      "*.ng_meta.json",
      "*.ng_summary.json"
    ],
    "projectHome": "D:\\code",
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "skittles"
    ]
  },
  "dartlang": {
    "sdkLocation": "C:\\tools\\dart-sdk",
    "sendUsage": false
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.2 (active)
atom-toolbar, v0.1.6 (active)
dark-flat-ui, v1.2.4 (inactive)
dartlang, v0.6.40 (active)
katana-syntax, v0.1.0 (inactive)
linter, v1.11.18 (active)
skittles, v0.0.0 (active)
synced-sidebar, v0.4.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
I think this might be caused by a recent Atom upgrade.

**Comment by KOGI** [comment]
Thank you!
