### ISSUE TITLE
Uncaught TypeError: t2.addEventListener$2 is not a function

### ISSUE THREAD

**Issue by forgemo** [dart-atom/dartlang#1098]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0-beta0
**Electron Version**: 1.3.6
**System**: Ubuntu 16.04.1
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.43

### Stack Trace

Uncaught TypeError: t2.addEventListener$2 is not a function

```
At /home/someuser/.atom/packages/dartlang/web/entry.dart.js:28587

TypeError: t2.addEventListener$2 is not a function
    at TooltipManager._tooltip$_install$0 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:65828:12)
    at TooltipManager$1 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:65847:16)
    at undefined.TooltipManager$ (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:65853:14)
    at TooltipController.dart.TooltipController._installInto$1 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:65798:11)
    at $constructor.<anonymous> (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:29904:32)
    at Workspace_observeTextEditors_closure.dart.Workspace_observeTextEditors_closure.call$1 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:49021:30)
    at undefined.Primitives_applyFunctionWithPositionalArguments (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:29569:28)
    at dart._callDartFunction (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:46383:31)
    at /home/someuser/.atom/packages/dartlang/web/entry.dart.js:46684:20
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom-beta/resources/app.asar/src/workspace.js:329:9)
    at JsObject.callMethod$2 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:46497:44)
    at Workspace.invoke$4 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:49432:23)
    at Workspace.invoke$2 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:49441:21)
    at Workspace.observeTextEditors$1 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:48971:40)
    at TooltipController_closure.call$0 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:65819:77)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:28962:23)
    at invokeClosure_closure.call$0 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:30852:29)
    at _IsolateContext.eval$1 (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:28578:25)
    at undefined._callInIsolate (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:28218:28)
    at dart.invokeClosure (/home/someuser/.atom/packages/dartlang/web/entry.dart.js:29804:20)
    at /home/someuser/.atom/packages/dartlang/web/entry.dart.js:29825:18
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dart-tools",
      "atom-toolbar",
      "save-commands",
      "language-rust"
    ],
    "followSymlinks": false,
    "telemetryConsent": "limited"
  },
  "dartlang": {
    "sdkLocation": "/usr/lib/dart",
    "sendUsage": false,
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-json-editor, v0.4.1 (active)
atom-toolbar, v0.1.6 (inactive)
dart-tools, v0.9.23 (inactive)
dartlang, v0.6.43 (inactive)
language-elm, v1.5.0 (inactive)
language-rust, v0.4.8 (inactive)
linter, v1.11.18 (active)
racer, v0.20.0 (active)
react, v0.16.1 (inactive)
rust-api-docs-helper, v0.5.1 (active)
save-commands, v0.6.11 (inactive)
synced-sidebar, v0.4.3 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report! Seems like something's regressed when run on `1.13.0-beta0`.
