### ISSUE TITLE
Uncaught TypeError J.getInterceptor$x(...).append$1 is not a function

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-atom/dartlang#1100]
I get this error whenever I open Atom with open dart files.

Stack trace:

```
TypeError: J.getInterceptor$x(...).append$1 is not a function
    at undefined.J.append$1$x (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:78513:41)
    at OutlineView._outline$_install$0 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:63354:11)
    at OutlineView$2 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:63591:16)
    at undefined.OutlineView$ (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:63597:14)
    at OutlineController.dart.OutlineController._handleEditor$1 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:63245:27)
    at $constructor.<anonymous> (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:29764:32)
    at Workspace_observeTextEditors_closure.dart.Workspace_observeTextEditors_closure.call$1 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:48875:30)
    at undefined.Primitives_applyFunctionWithPositionalArguments (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:29429:28)
    at dart._callDartFunction (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:46237:31)
    at /Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:46538:20
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at JsObject.callMethod$2 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:46351:44)
    at Workspace.invoke$4 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:49286:23)
    at Workspace.invoke$2 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:49295:21)
    at Workspace.observeTextEditors$1 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:48825:40)
    at OutlineController_closure1.call$0 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:63296:67)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:28822:23)
    at invokeClosure_closure.call$0 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:30712:29)
    at _IsolateContext.eval$1 (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:28438:25)
    at undefined._callInIsolate (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:28078:28)
    at dart.invokeClosure (/Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:29664:20)
    at /Users/jacehensley/.atom/packages/dartlang/web/entry.dart.js:29685:18
```

I am using Atom 1.13.0-beta1 with Dart 1.19.1.

**Comment by devoncarew** [comment]
Hmm, sounds like a regression when run with `1.13.0-beta`.

**Comment by devoncarew** [comment]
Worked around the issue in https://github.com/dart-atom/dartlang/commit/f076c5e3b51f1ba45680961ad63e60d3c4eb4561 - the outline is disabled for versions of Atom that no longer implement their components using shadow DOM.
