### ISSUE TITLE
Analysis server shutting down - no logs

### ISSUE THREAD

**Issue by jtmcdole** [dart-atom/dartlang#1103]
- Hit 'start'
- Watch it analyze files
- Watch it shut down for no reason.

Atom 1.12.2, dartlang 0.6.45, SDK 1.21.0-dev.3.0 running on linux.

**Comment by devoncarew** [comment]
Hey @jtmcdole! I suspect that this is an issue with the internal SDK and build of the analysis server.

Can you:
- enable verbose logging in the `dartlang` plugin settings (dial it up to `finer`)
- open the devtools console in atom
- restart atom and look for errors in the console

It's likely that you'll see that the analysis server dying as a result of a 'dropbox' process. This is something we saw from another user today. No resolution as yet; /cc @skybrian.

**Comment by jtmcdole** [comment]
Indeed, there was a dropbox error. Is there a way to disable dropbox uploading (note: I disabled analytics and still got this error after restarting Atom)?

```code
severe • analysis-server: Unhandled exception:
Bad state: dropbox process exited with code=1, stderr:
Can't connect to App Engine: RPC::DEADLINE_EXCEEDED: rpc.ClientConn(blade:apphosting-frontend): no addresses received before deadline
#0      uploadDropbox.<uploadDropbox_async_body> (package:dart.tools.silo/upload.dart:26)
#1      _RootZone.runUnary (dart:async/zone.dart:1412)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      Future.wait.<anonymous closure> (dart:async/future.dart:300)
#7      _RootZone.runUnary (dart:async/zone.dart:1412)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#11     _Future._complete (dart:async/future_impl.dart:467)
#12     Stream.fold.<anonymous closure> (dart:async/stream.dart:647)
#13     _RootZone.runGuarded (dart:async/zone.dart:1335)
#14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:278)
#17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:95)
#18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:18)
#19     _StringAdapterSink.close (dart:convert/string_conversion.dart:267)
#20     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:324)
#21     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:96)
#22     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:140)
#23     _RootZone.runGuarded (dart:async/zone.dart:1335)
#24     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#25     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#26     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:278)
#27     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:776)
#28     _StreamController._closeUnchecked (dart:async/stream_controller.dart:624)
#29     _StreamController.close (dart:async/stream_controller.dart:617)
#30     _Socket._onData (dart:io-patch/socket_patch.dart:1687)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1346)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#34     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#35     _StreamController._add (dart:async/stream_controller.dart:635)
#36     _StreamController.add (dart:async/stream_controller.dart:581)
#37     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1254)
#38     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:774)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
native_typed_data.dart:397 fine • process: exit code: 255 (/usr/lib/google-dartlang/bin/dart)
native_typed_data.dart:397 fine • analysis-server: exited with code 255
```

**Comment by devoncarew** [comment]
Closing - this was an internal issue; it's generally resolved by a machine reboot.
