### ISSUE TITLE
Analyzer RequestError

### ISSUE THREAD

**Issue by jxson** [dart-atom/dartlang#1110]
[Enter steps to reproduce below:]

1. apm install dartlang
2. Open a Dart project

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.45

### Stack Trace

Uncaught 

```
At <snip>.atom/packages/dartlang/web/entry.dart.js:28460

[Analyzer RequestError method: analysis.reanalyze, code: SERVER_ERROR, message: NoSuchMethodError: The getter 'addedFiles' was called on null.
Receiver: null
Tried calling: addedFiles]
    at undefined.wrapException (<snip>.atom/packages/dartlang/web/entry.dart.js:29529:17)
    at _rootHandleUncaughtError_closure.call$0 (<snip>.atom/packages/dartlang/web/entry.dart.js:34813:19)
    at undefined._microtaskLoop (<snip>.atom/packages/dartlang/web/entry.dart.js:32214:27)
    at $constructor.dart._startMicrotaskLoop (<snip>.atom/packages/dartlang/web/entry.dart.js:32220:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (<snip>.atom/packages/dartlang/web/entry.dart.js:28835:23)
    at invokeClosure_closure.call$0 (<snip>.atom/packages/dartlang/web/entry.dart.js:30725:29)
    at _IsolateContext.eval$1 (<snip>.atom/packages/dartlang/web/entry.dart.js:28451:25)
    at undefined._callInIsolate (<snip>.atom/packages/dartlang/web/entry.dart.js:28091:28)
    at dart.invokeClosure (<snip>.atom/packages/dartlang/web/entry.dart.js:29677:20)
    at <snip>.atom/packages/dartlang/web/entry.dart.js:29698:18
```

### Commands

```
     -6:45.9.0 flutter:enable (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:45.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:46.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:39.5.0 core:close (atom-pane.pane.active)
     -2:39.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:38.1.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:37.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:03.8.0 core:close (div.panels-item)
  2x -2:03.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:26.1.0 command-palette:toggle (input.hidden-input)
     -1:21.1.0 core:confirm (input.hidden-input)
     -1:21.1.0 dartlang:analysis-server-status (input.hidden-input)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "projectHome": "~/Code",
    "telemetryConsent": "limited",
    "useCustomTitleBar": true
  },
  "dartlang": {
    "formatOnSave": true,
    "sdkLocation": "<snip>Code/fuchsia/lib/flutter/bin/cache/dart-sdk",
    "showInfos": true,
    "showOutlineView": false,
    "showTodos": true,
    "useErrorsView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6 (active)
dartlang, v0.6.45 (active)
editorconfig, v2.1.0 (active)
file-icons, v2.0.8 (active)
flutter, v0.2.6 (active)
jshint, v1.8.6 (active)
language-elm, v1.5.0 (active)
language-gn, v0.2.0 (active)
language-mojom, v0.0.1 (active)
language-rust, v0.4.8 (active)
linter, v1.11.21 (active)
linter-rust, v0.7.2 (active)
release-notes, v0.53.0 (active)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.8.1 (active)
synced-sidebar, v0.4.3 (active)
title-case, v0.4.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dvdwasibi** [comment]
I'm also getting this error.
