### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getModel' of undefined

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#1116]
It looks like much of our interop as regressed:

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package 0.6.45

### Stack Trace

Uncaught TypeError: Cannot read property 'getModel' of undefined

```
At /Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:15

TypeError: Cannot read property 'getModel' of undefined
    at self.getTextEditorForElement (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:15:68)
    at JsFunction.apply$2$thisArg (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:46823:48)
    at JsFunction.apply$1 (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:46826:21)
    at undefined.promptUser (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:48608:99)
    at FindTypeHelper._handleFindType$1 (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:52120:11)
    at FindTypeHelper_closure.call$1 (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:52159:27)
    at CommandRegistry_add_closure.dart.CommandRegistry_add_closure.call$1 (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:48285:23)
    at undefined.Primitives_applyFunctionWithPositionalArguments (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:29486:28)
    at dart._callDartFunction (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:46634:31)
    at atom-text-editor.<anonymous> (/Users/devoncarew/projects/atom/dartlang/web/entry.dart.js:46936:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

**Comment by djcohen66** [comment]
Was there a resolution to the bug.  I am working through a dart tutorial and I am receiving this bug trying to run a test.

**Comment by devoncarew** [comment]
Ah, I assumed this has been fixed as part of recompiling with the latest dart2js. Can you post the version of the plugin that you're using (and perhaps the first few lines of your stack trace)?

**Comment by djcohen66** [comment]
TypeError: Cannot read property 'getModel' of undefined
    at self.getTextEditorForElement (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:15:68)
    at JsFunction.apply$2$thisArg (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:47014:48)
    at JsFunction.apply$1 (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:47017:21)
    at Object.promptUser (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:48569:99)
    at PubManager._handleRun$2$editor$path (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:63960:11)
    at PubManager._handleRun$1$path (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:63963:21)
    at PubManager_closure6.call$1 (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:64107:20)
    at PubManager__addSdkCmd_closure.call$1 (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:64122:25)
    at CommandRegistry_add_closure.dart.CommandRegistry_add_closure.call$1 (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:48247:23)
    at Object.Primitives_applyFunctionWithPositionalArguments (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:29551:28)
    at dart._callDartFunction (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:46823:14)
    at HTMLDivElement.<anonymous> (C:\Users\David\.atom\packages\dartlang\web\entry.dart.js:47127:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\David\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (C:\Users\David\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\David\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\David\AppData\Local\atom\app-1.19.0\resources\app\src\atom-environment.js:1344:34)
    at EventEmitter.outerCallback (C:\Users\David\AppData\Local\atom\app-1.19.0\resources\app\src\application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
