### ISSUE TITLE
Uncaught Exception: undefined.wrapException

### ISSUE THREAD

**Issue by darkn3rd** [dart-atom/dartlang#1121]
**Atom**: 1.15.0
**Electron**: 1.3.13
**Chrome**: 52.0.2743.82
**Node**: 6.5.0
**Mac OS X: 10.12.4
**dartlang package**: 0.6.45

```
/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:28449


Error: Command failed: /bin/bash -l -c 'printenv'
Unable to find any JVMs matching version "1.8".
No Java runtime present, try --request to install.
/Users/jmenchaca/.profile: line 14: perl: command not found
/bin/bash: printenv: command not found
    at undefined.wrapException (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:29517:17)
    at undefined.execSync (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:48507:17)
    at ShellWrangler$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:48693:68)
    at undefined.ShellWrangler$ (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:48712:14)
    at undefined.which (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:47751:18)
    at SdkDiscovery._discoverSdk$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:69136:20)
    at SdkDiscovery.discoverSdk$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:69132:21)
    at SdkManager.tryToAutoConfigure$1$verbose (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:68883:37)
    at SdkManager.tryToAutoConfigure$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:68886:21)
    at SdkManager_closure.call$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:69023:22)
    at closure0.call$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:32822:37)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:28824:23)
    at invokeClosure_closure.call$0 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:30712:29)
    at _IsolateContext.eval$1 (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:28440:25)
    at undefined._callInIsolate (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:28080:28)
    at dart.invokeClosure (/Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:29665:20)
    at /Users/jmenchaca/.atom/packages/dartlang/web/entry.dart.js:29686:18
```

**Comment by schwa423** [comment]
Here is another one.  Atom said that this had already been reported, but other than terminating at wrapException(), these two issues have nothing to do with one another:

```
[Analyzer RequestError method: analysis.setAnalysisRoots, code: SERVER_ERROR, message: FileSystemException(path=/home/josh/code/fuchsia/out/debug-x86-64/gen/dart.sources/; message=Directory listing failed)]
    at undefined.wrapException (/home/josh/.atom/packages/dartlang/web/entry.dart.js:29517:17)
    at _rootHandleUncaughtError_closure.call$0 (/home/josh/.atom/packages/dartlang/web/entry.dart.js:34781:19)
    at undefined._microtaskLoop (/home/josh/.atom/packages/dartlang/web/entry.dart.js:32183:27)
    at $constructor.dart._startMicrotaskLoop (/home/josh/.atom/packages/dartlang/web/entry.dart.js:32189:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/josh/.atom/packages/dartlang/web/entry.dart.js:28824:23)
    at invokeClosure_closure.call$0 (/home/josh/.atom/packages/dartlang/web/entry.dart.js:30712:29)
    at _IsolateContext.eval$1 (/home/josh/.atom/packages/dartlang/web/entry.dart.js:28440:25)
    at undefined._callInIsolate (/home/josh/.atom/packages/dartlang/web/entry.dart.js:28080:28)
    at dart.invokeClosure (/home/josh/.atom/packages/dartlang/web/entry.dart.js:29665:20)
    at /home/josh/.atom/packages/dartlang/web/entry.dart.js:29686:18
```

**Comment by sethbergman** [comment]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Linux Mint
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.46


### Stack Trace

Uncaught 

```
At /home/seth/.atom/packages/dartlang/web/entry.dart.js:28460

Error: not opened
    at WebSocket.send (/home/seth/.atom/packages/dartlang/node_modules/ws/lib/WebSocket.js:219:16)
    at JsObject.callMethod$2 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:46364:44)
    at ObservatoryDebugger_connect__closure0.call$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:57992:21)
    at VmService._vm_service_lib$_call$2 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:74184:44)
    at ObservatoryIsolate._updateIsolateInfo$0 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:58650:29)
    at ObservatoryConnection._registerNewIsolate$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:58181:24)
    at ObservatoryConnection._registerNewIsolates$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:58187:29)
    at ObservatoryConnection__init_closure8.dart.ObservatoryConnection__init_closure8.call$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:58370:19)
    at _RootZone.runUnary$2 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:34891:20)
    at _FutureListener.handleValue$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:32992:34)
    at _Future__propagateToListeners_handleValueCallback.call$0 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:33453:60)
    at undefined._Future__propagateToListeners (/home/seth/.atom/packages/dartlang/web/entry.dart.js:33312:104)
    at _Future._completeWithValue$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:33174:11)
    at _Future__asyncComplete_closure0.call$0 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:33391:20)
    at undefined._microtaskLoop (/home/seth/.atom/packages/dartlang/web/entry.dart.js:32214:27)
    at $constructor.dart._startMicrotaskLoop (/home/seth/.atom/packages/dartlang/web/entry.dart.js:32220:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:28835:23)
    at invokeClosure_closure.call$0 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:30725:29)
    at _IsolateContext.eval$1 (/home/seth/.atom/packages/dartlang/web/entry.dart.js:28451:25)
    at undefined._callInIsolate (/home/seth/.atom/packages/dartlang/web/entry.dart.js:28091:28)
    at dart.invokeClosure (/home/seth/.atom/packages/dartlang/web/entry.dart.js:29677:20)
    at /home/seth/.atom/packages/dartlang/web/entry.dart.js:29698:18
```

### Commands

```
     -2:01.0 dartlang:pub-global-run (div.header.list-item.project-root-header)
  5x -1:58.9.0 core:backspace (input.hidden-input)
     -1:57.6.0 core:confirm (input.hidden-input)
     -1:54.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -1:50 dartlang:pub-run (span.name.icon.dart-icon.medium-cyan)
     -1:43.6.0 core:confirm (input.hidden-input)
  6x -1:37.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:38.1.0 dartlang:run-application (span.name.icon.dart-icon.medium-cyan)
  3x -0:28 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:00.6.0 dartlang:run-application (span.name.icon.dart-icon.medium-cyan)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "fancy-bracket-matcher",
      "angular-2",
      "ionic-preview",
      "angular2-snippets-atom",
      "autocomplete-angular-material",
      "language-vue",
      "linter-eslint",
      "linter-tslint",
      "language-gfm",
      "project-manager",
      "linter-markdown",
      "angular2"
    ],
    "followSymlinks": false,
    "projectHome": "/home/seth/lab",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "dartlang": {
    "sdkLocation": "/usr/lib/dart",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
angular-2, v0.2.6 (inactive)
angular-2-typeScript-snippets, v0.6.3 (active)
angular2, v0.1.1 (inactive)
angular2-snippets-atom, v0.7.0 (inactive)
angularjs, v0.4.0 (active)
angularjs-snippets, v0.10.18 (active)
angularjs-styleguide-snippets, v0.9.1 (active)
atom-bracket-highlight, v0.3.2 (active)
atom-brackets-glow, v0.4.0 (inactive)
atom-like-brackets-editor, v1.1.4 (active)
atom-markdown-auto-preview, v1.1.1 (active)
atom-material-syntax, v1.0.2 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-toolbar, v0.1.6 (active)
atom-typescript, v11.0.2 (inactive)
autocomplete-angular-material, v0.4.0 (inactive)
autocomplete-js-import, v1.4.0 (active)
dark-flat-ui, v1.2.4 (inactive)
dartlang, v0.6.46 (active)
fancy-bracket-matcher, v1.0.1 (inactive)
file-icons, v2.1.3 (active)
ionic-preview, v0.7.0 (inactive)
language-markdown, v0.21.0 (active)
language-markdown-in-js, v1.0.2 (active)
language-vue, v0.21.2 (inactive)
linter, v1.11.23 (active)
linter-eslint, v8.1.4 (inactive)
linter-markdown, v3.1.0 (inactive)
linter-tslint, v0.14.0 (inactive)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-plus, v2.4.9 (active)
markdown-writer, v2.6.4 (inactive)
minimap, v4.27.1 (active)
project-manager, v3.3.3 (inactive)
synced-sidebar, v0.4.3 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (active)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
