### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by vcsala** [dart-atom/dartlang#1145]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package 0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /Users/Viktor/.atom/packages/dartlang/web/entry.dart.js:28564

TypeError: Cannot read property 'apply' of undefined
    at /packages/dartlang/web/entry.dart.js:47100:43)
    at /packages/dartlang/web/entry.dart.js:47103:21)
    at /packages/dartlang/web/entry.dart.js:49986:23)
    at /packages/dartlang/web/entry.dart.js:49990:21)
    at /packages/dartlang/web/entry.dart.js:48983:101)
    at /packages/dartlang/web/entry.dart.js:28933:23)
    at /packages/dartlang/web/entry.dart.js:30858:29)
    at /packages/dartlang/web/entry.dart.js:28556:25)
    at Object._callInIsolate (/packages/dartlang/web/entry.dart.js:28202:28)
    at dart.invokeClosure (/packages/dartlang/web/entry.dart.js:29797:20)
    at /packages/dartlang/web/entry.dart.js:29818:18
```

### Commands

```
     -3:50.1.0 core:move-down (input.hidden-input)
     -3:49.2.0 core:save (input.hidden-input)
  2x -3:48.9.0 core:move-down (input.hidden-input)
     -3:48.2.0 core:move-up (input.hidden-input)
     -3:47.6.0 dartlang:newline (input.hidden-input)
     -3:47.6.0 editor:newline (input.hidden-input)
     -3:47.3.0 dartlang:newline (input.hidden-input)
     -3:47.3.0 editor:newline (input.hidden-input)
 10x -3:41 core:backspace (input.hidden-input)
     -3:31.8.0 dartlang:newline (input.hidden-input)
     -3:31.8.0 editor:newline (input.hidden-input)
     -0:41.8.0 core:move-right (input.hidden-input)
  3x -0:40.8.0 core:backspace (input.hidden-input)
     -0:24.7.0 dartlang:refactor-rename (span.syntax--support.syntax--class.syntax--dart)
  2x -0:12.8.0 core:backspace (input.hidden-input)
     -0:03.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-htmltidy 5.1.0 
atom-toolbar 0.1.6 
autocomplete-clang 0.11.3 
busy-signal 1.4.3 
dartlang 0.7.0 
intentions 1.1.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.7 
synced-sidebar 0.4.3 
```

**Comment by jungletech** [comment]
Similar thing

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package 0.7.0


### Stack Trace

Uncaught 

```
At /Users/williamjung/.atom/packages/dartlang/web/entry.dart.js:28564

app 'c103b12a-9047-4b4e-b8f5-a6e60f750017' not found
    at Object.wrapException (/packages/dartlang/web/entry.dart.js:29649:17)
    at /packages/dartlang/web/entry.dart.js:34840:19)
    at Object._microtaskLoop (/packages/dartlang/web/entry.dart.js:32280:27)
    at StaticClosure.dart._startMicrotaskLoop (/packages/dartlang/web/entry.dart.js:32286:11)
    at /packages/dartlang/web/entry.dart.js:28933:23)
    at /packages/dartlang/web/entry.dart.js:30858:29)
    at /packages/dartlang/web/entry.dart.js:28556:25)
    at Object._callInIsolate (/packages/dartlang/web/entry.dart.js:28202:28)
    at dart.invokeClosure (/packages/dartlang/web/entry.dart.js:29797:20)
    at /packages/dartlang/web/entry.dart.js:29818:18
```

### Commands

```
     -2:48.7.0 flutter:enable (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:33.5.0 flutter:create-project (summary.welcome-summary.icon.icon-repo)
 27x -2:30.5.0 core:backspace (summary.welcome-summary.icon.icon-repo)
     -2:18.4.0 core:confirm (input.hidden-input)
     -2:00.1.0 tree-view:reveal-active-file (atom-text-editor.editor)
     -1:39.6.0 dartlang:run-application (input.hidden-input)
```

### Non-Core Packages

```
atom-toolbar 0.1.6 
busy-signal 1.4.3 
dartlang 0.7.0 
flutter 0.2.6 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.7 
```

`

**Comment by melusi-k** [comment]
Same here

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: elementary OS
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package 0.7.1


### Stack Trace

Uncaught 

```
At /home/melusi/.atom/packages/dartlang/web/entry.dart.js:31128

TypeError: Cannot read property 'apply' of undefined
    at undefined.wrapException (/packages/dartlang/web/entry.dart.js:32213:17)
    at /packages/dartlang/web/entry.dart.js:37511:19)
    at undefined._microtaskLoop (/packages/dartlang/web/entry.dart.js:34877:27)
    at /packages/dartlang/web/entry.dart.js:34883:11)
    at /packages/dartlang/web/entry.dart.js:31497:23)
    at /packages/dartlang/web/entry.dart.js:33455:29)
    at /packages/dartlang/web/entry.dart.js:31120:25)
    at undefined._callInIsolate (/packages/dartlang/web/entry.dart.js:30766:28)
    at dart.invokeClosure (/packages/dartlang/web/entry.dart.js:32361:20)
    at /packages/dartlang/web/entry.dart.js:32382:18
```

### Commands

```
     -0:19.9.0 flutter:enable (atom-workspace.workspace.scrollbars-visible-always.theme-chestnut-light-atom-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.15 
chestnut-light-atom-syntax 0.2.1 
dartlang 0.7.1 
flutter 0.2.7 
hey-pane 1.0.0 
linter-write-good 0.9.0 
pristine-ui 1.1.10 
```

**Comment by perfectpapa** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package 0.7.1


### Stack Trace

Uncaught 

```
At /Users/wx/.atom/packages/dartlang/web/entry.dart.js:31128

app 'f931ca19-b43f-41fe-8ce0-902aac81bc54' not found
    at Object.wrapException (/packages/dartlang/web/entry.dart.js:32213:17)
    at /packages/dartlang/web/entry.dart.js:37511:19)
    at Object._microtaskLoop (/packages/dartlang/web/entry.dart.js:34877:27)
    at StaticClosure.dart._startMicrotaskLoop (/packages/dartlang/web/entry.dart.js:34883:11)
    at /packages/dartlang/web/entry.dart.js:31497:23)
    at /packages/dartlang/web/entry.dart.js:33455:29)
    at /packages/dartlang/web/entry.dart.js:31120:25)
    at Object._callInIsolate (/packages/dartlang/web/entry.dart.js:30766:28)
    at dart.invokeClosure (/packages/dartlang/web/entry.dart.js:32361:20)
    at /packages/dartlang/web/entry.dart.js:32382:18
```

### Commands

```
  5x -1:04.5.0 core:backspace (input.hidden-input)
     -1:02.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-toolbar 0.1.6 
busy-signal 1.4.3 
dartlang 0.7.1 
emmet 2.4.3 
file-icons 2.1.13 
flutter 0.2.7 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.10 
```
