### ISSUE TITLE
Uncaught Uncaught Error: [RequestError code: UNANALYZED_PRIORITY_FILES, message: Unanalyzed files...

### ISSUE THREAD

**Issue by eseidel** [dart-atom/dartlang#157]
I just installed atom and dartlang on my personal machine.  I did not restart atom since installing dartlang.

I created a new empty directory with a lib directory, empty main.dart and a pubspec.yaml containing only "name: foo" and ran pub get.

Then I opened main.dart in atom and got this:

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.3.9

### Stack Trace

Uncaught Uncaught Error: [RequestError code: UNANALYZED_PRIORITY_FILES, message: Unanalyzed files cannot be a priority: '/Stuff/Projects/foo/lib/main.dart']

```
At /Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:14318

Uncaught Error: [RequestError code: UNANALYZED_PRIORITY_FILES, message: Unanalyzed files cannot be a priority: '/Stuff/Projects/foo/lib/main.dart']
  at [object Object].dart.wrapException (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:15260:17)
  at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:27342:17)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:25710:30)
  at [object Object].dart._microtaskLoop (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:24421:12)
  at [object Object].dart._microtaskLoopEntry (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:24427:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:14693:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:16345:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:14309:25)
  at [object Object].dart._callInIsolate (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:13940:28)
  at dart.invokeClosure (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:15408:18)
  at /Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:15429:18

```

### Commands

```
     -5:33.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:32 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:53.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:52.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:29.2.0 window:install-shell-commands (div.settings-view.pane-item)
```

### Config

```json
{
  "dartlang": {
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.3.9

# Dev
No dev packages
```

**Comment by eseidel** [comment]
After restarting Atom I got the same error.

**Comment by eseidel** [comment]
It's probable that my Dart SDK version is old.

**Comment by eseidel** [comment]
I have dartanalyzer version 1.9.1 installed from homebrew

**Comment by eseidel** [comment]
Updated to dartanalyzer version 1.11.1 and the error appears to have gone away.  Presumably the dartlang plugin could just detect an incompatible version and show a better error.   Glad to have it resolved regardless.

**Comment by devoncarew** [comment]
I've only tried the plugin with the dev (1.12) sdk. I think the resolutions here are that we need to:
- verify that the plugin works with the current stable sdk (which I think you've done)
- warn if the user has a plugin older than that
- set up bots to test on the current stable sdk and the latest dev sdk

Realistically we're not going to spend the effort to run w/ sdks older than stable, but we should warn the user that things won't work well. The automated testing is something we'll get to; it'll require a few weeks of effort.

**Comment by eseidel** [comment]
I would just refuse to load with anything other than the absolute latest
sdk. As you said, we're too poor to worry about anything older than that.

**Comment by devoncarew** [comment]
Added testing issues here https://github.com/dart-atom/dartlang/issues/162 and here https://github.com/dart-atom/dartlang/issues/161. I'll add a fast-fail message if we don't meet our min sdk requirements -

**Comment by eseidel** [comment]
I hit this just now with:
Dart VM version: 1.12.0-dev.4.0 (Tue Jul 21 03:40:25 2015) on "macos_x64"
When creating a new empty file in my package `bin/duel.dart`

So this is clearly not limited to the SDK version. :(

```
**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.3.9


### Stack Trace

Uncaught Uncaught Error: [RequestError code: UNANALYZED_PRIORITY_FILES, message: Unanalyzed files cannot be a priority: '/Stuff/Projects/lol_duel/bin/duel.dart']

```
At /Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:495

Uncaught Error: [RequestError code: UNANALYZED_PRIORITY_FILES, message: Unanalyzed files cannot be a priority: '/Stuff/Projects/lol_duel/bin/duel.dart']
  at [object Object].dart.wrapException (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:15260:17)
  at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:27342:17)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:25710:30)
  at [object Object].dart._microtaskLoop (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:24421:12)
  at [object Object].dart._microtaskLoopEntry (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:24427:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:14693:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:16345:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:14309:25)
  at [object Object].dart._callInIsolate (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:13940:28)
  at dart.invokeClosure (/Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:15408:18)
  at /Users/eseidel/.atom/packages/dartlang/web/entry.dart.js:15429:18

```

### Commands

```
     -4:24 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -4:23.5.0 core:save (atom-text-editor.editor.is-focused)
  6x -1:47.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:39.7.0 editor:newline (atom-text-editor.editor.is-focused)
 17x -1:35.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:27.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:24.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:17.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:16.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:14.5.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:06.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:44.4.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:18.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:16.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "dartlang": {
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
dartlang, v0.3.10
linter, v1.3.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by eseidel** [comment]
I seem to get this error whenever I switch to my `main/duel.dart`.  If you have debugging suggestions, I'm happy to investigate locally.

**Comment by devoncarew** [comment]
@eseidel, can you zip up your project and send it to me? I see a guard in our code to make sure that we don't send in a path to the analysis server as a 'priority file' if it's not in a dart project. Which is the check I was going to put in to fix this bug :) So I'd like a test case to be able to dig into why this is happening.

**Comment by eseidel** [comment]
Here is the code: https://github.com/eseidel/lolsim  Any time I open duel.dart it throws the error.

**Comment by devoncarew** [comment]
Hmm, I cloned the repo but can't reproduce the error. So, that's maybe good and bad news. I'll reduce the severity of the error - still log it but not throw an exception through to the top level. We can keep this issue open to collect any more info / people hitting it.

**Comment by devoncarew** [comment]
https://github.com/dart-atom/dartlang/pull/166 https://github.com/dart-atom/dartlang/pull/167

**Comment by devoncarew** [comment]
Addressed as part of later builds.
