### ISSUE TITLE
Uncaught Uncaught Error: NullError: method not found: 'scope' on nullStack Trace:TypeError: Can...

### ISSUE THREAD

**Issue by tomaszkubacki** [dart-atom/dartlang#158]
This error is generated when anlyzer is starting working on my Dart project (unfortunetly proprietary/closed source - can't share)

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.3.9

### Stack Trace

Uncaught Uncaught Error: NullError: method not found: 'scope' on null
Stack Trace:
TypeError: Cannot read property 'scope' of null
    at MessageRegistry.set (/Users/tomek/.atom/packages/linter/lib/message-registry.coffee:46:17)
    at Linter.setMessages (/Users/tomek/.atom/packages/linter/lib/linter-plus.coffee:81:28)
    at JsObject.dart.JsObject.callMethod$2 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:32738:44)
    at LinterService.dart.ProxyHolder.invoke$4 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:20765:27)
    at LinterService.dart.ProxyHolder.invoke$3 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:20778:21)
    at LinterService.dart.LinterService.setMessages$2 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:20928:14)
    at DartLinterConsumer.dart.DartLinterConsumer._emit$1 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:34369:25)
    at DartLinterConsumer.dart.DartLinterConsumer._regenErrors$0 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:34346:14)
    at DartLinterConsumer_consume_closure.dart.DartLinterConsumer_consume_closure.call$1 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:34400:46)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:27373:20)

```
At /Users/tomek/.atom/packages/dartlang/web/entry.dart.js:14318

Uncaught Error: NullError: method not found: 'scope' on null
Stack Trace:
TypeError: Cannot read property 'scope' of null
    at MessageRegistry.set (/Users/tomek/.atom/packages/linter/lib/message-registry.coffee:46:17)
    at Linter.setMessages (/Users/tomek/.atom/packages/linter/lib/linter-plus.coffee:81:28)
    at JsObject.dart.JsObject.callMethod$2 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:32738:44)
    at LinterService.dart.ProxyHolder.invoke$4 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:20765:27)
    at LinterService.dart.ProxyHolder.invoke$3 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:20778:21)
    at LinterService.dart.LinterService.setMessages$2 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:20928:14)
    at DartLinterConsumer.dart.DartLinterConsumer._emit$1 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:34369:25)
    at DartLinterConsumer.dart.DartLinterConsumer._regenErrors$0 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:34346:14)
    at DartLinterConsumer_consume_closure.dart.DartLinterConsumer_consume_closure.call$1 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:34400:46)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:27373:20)
    at dart.wrapException (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:15260:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:27342:17)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:25710:30)
    at dart._microtaskLoop (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:24421:12)
    at dart._microtaskLoopEntry (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:24427:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:14693:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:16345:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:14309:25)
    at dart._callInIsolate (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:13940:28)
    at dart.invokeClosure (/Users/tomek/.atom/packages/dartlang/web/entry.dart.js:15408:18)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "dartlang": {
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.3.9
linter, v1.3.0

# Dev
No dev packages
```

**Comment by eseidel** [comment]
I just hit this as well.  This must be a regression in the latest build @devoncarew  This is the entirety of my dart project:

import 'dart:convert';

void main() {
  int lineNumber = 1;
  Stream<List<int>> stream = new File('quotes.txt').openRead();

  stream.transform(JSON.decoder)
        .transform(const LineSplitter())
        .listen((line) {
          if (showLineNumbers) {
            stdout.write('${lineNumber++} ');
          }
          stdout.writeln(line);
        });
}

**Comment by eseidel** [comment]
I'm just constantly getting these as I try to type.  Probably a dart-sdk version mis-match again.  I'm using dartanalyzer version 1.11.1 it's possible that dartlang has dependencies on the dev channel.

**Comment by eseidel** [comment]
I just used homebrew to switch to the dev channel, i'm now using `dartanalyzer version 1.12.0-dev.4.0` however I'm still getting these errors.

**Comment by agray86** [comment]
It looks like it's some sort of issue interacting with the newest linter package (1.3.0).  I was able to resolve this on my machine by downgrading the linter package to 1.2.4 via apm.

**Comment by eseidel** [comment]
@devoncarew this makes dartlang unusable at the moment.  The dialogs are non-stop.

`apm install linter@1.2.4` does seem to work around the problem, thanks @agray86!

**Comment by devoncarew** [comment]
Thanks the reports! Afk at the moment, but will push out a patch once I'm
back.

**Comment by steelbrain** [comment]
@devoncarew A rough look at the stack trace gives me a hint that you **might** be passing a null when setting messages.

**Comment by devoncarew** [comment]
Yup, I have a line on the issue. We are passing `null` - looks like that was ok w/ older version but not the latest. I'll change this to pass a real value for the provider.

**Comment by devoncarew** [comment]
Just published a new version - we should not work w/ the previous and current versions of `linter`.

Thanks for the reports and the investigations!
