### ISSUE TITLE
stack trace analyzing dart-protoc-plugin

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#169]
Uncaught Error: [RequestError code: UNANALYZED_PRIORITY_FILES, message: Unanalyzed files cannot be a priority: '/google/src/cloud/skybrian/dart-work/eng/skybrian/dart-protoc-plugin/test/all_tests.dart']
    at dart.wrapException (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:15261:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:27343:17)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:25711:30)
    at dart._microtaskLoop (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:24422:12)
    at dart._microtaskLoopEntry (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:24428:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:14694:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:16346:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:14310:25)
    at dart._callInIsolate (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:13941:28)
    at dart.invokeClosure (/usr/local/google/home/skybrian/.atom/packages/dartlang/web/entry.dart.js:15409:18)

**Comment by skybrian** [comment]
It seems to be reproducible. I tried rebuilding the plugin using "make run-tests" and Dart->Re-analyze sources and got the same result.

**Comment by devoncarew** [comment]
Related to https://github.com/dart-atom/dartlang/issues/157.

**Comment by devoncarew** [comment]
Just to verify, you have a pubspec here:, `/google/src/cloud/skybrian/dart-work/eng/skybrian/dart-protoc-plugin/`? Is that the directory you opened in atom?

**Comment by devoncarew** [comment]
Closing as I suspect it's the same underlying issue as #157.
