### ISSUE TITLE
Uncaught Uncaught Error: Error: This socket has been ended by the other partyStack Trace:Error:...

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-atom/dartlang#201]
If you "killall dart" from a terminal (as we sometimes do for other reasons) you get this horrible message (multiple times!) from the dartlang plugin.  We should give a better message or recover gracefully.

**Atom Version**: 1.0.5
**System**: Ubuntu 14.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.3.12

### Stack Trace

Uncaught Uncaught Error: Error: This socket has been ended by the other party
Stack Trace:
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at JsObject.dart.JsObject.callMethod$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:33447:44)
    at _AnalysisServerWrapper__messageWriter_closure.dart._AnalysisServerWrapper__messageWriter_closure.call$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:19300:14)
    at _AnalysisServerWrapper.dart.Server._writeMessage$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:17559:35)
    at _AnalysisServerWrapper.dart.Server._call$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:17530:14)
    at AnalysisServer.dart.AnalysisServer._focusedEditorChanged$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:18792:21)
    at null.<anonymous> (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:15785:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:28057:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:27202:20)
    at _DelayedData.dart._DelayedData.perform$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:27396:18)

```
At /usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:14595

Uncaught Error: Error: This socket has been ended by the other party
Stack Trace:
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at JsObject.dart.JsObject.callMethod$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:33447:44)
    at _AnalysisServerWrapper__messageWriter_closure.dart._AnalysisServerWrapper__messageWriter_closure.call$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:19300:14)
    at _AnalysisServerWrapper.dart.Server._writeMessage$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:17559:35)
    at _AnalysisServerWrapper.dart.Server._call$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:17530:14)
    at AnalysisServer.dart.AnalysisServer._focusedEditorChanged$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:18792:21)
    at null.<anonymous> (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:15785:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:28057:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:27202:20)
    at _DelayedData.dart._DelayedData.perform$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:27396:18)
    at dart.wrapException (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:15537:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:28026:17)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:26352:30)
    at dart._microtaskLoop (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:25063:12)
    at dart._microtaskLoopEntry (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:25069:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:14970:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:16622:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:14586:25)
    at dart._callInIsolate (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:14226:28)
    at dart.invokeClosure (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:15685:18)
```

### Commands

```
     -4:45.5.0 editor:newline (atom-text-editor.editor.is-focused)
 18x -4:43 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:34.4.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -4:29.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:21.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:21.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -4:19.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:18.3.0 core:paste (atom-text-editor.editor.is-focused)
  2x -4:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -4:13.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.7.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "dartlang": {
    "sdkLocation": "/usr/local/google/home/eseidel/Downloads/dart-sdk"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.3.12
linter, v1.3.2

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Yup, something like a single message that says `Oops, the analysis server stopped!`, and possibly a button available to re-start it.
