### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith$1' of null

### ISSUE THREAD

**Issue by mit-mit** [dart-atom/dartlang#208]
[Enter steps to reproduce below:]

Sorry don't have repro steps, this just threw as I was reading through some code

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.4
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.3.14

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith$1' of null

```
At /Users/mit/.atom/packages/dartlang/web/entry.dart.js:84

TypeError: Cannot read property 'endsWith$1' of null
  at [object Object].dart.basename (/Users/mit/.atom/packages/dartlang/web/entry.dart.js:21821:13)
  at PubContextCommand.dart.PubContextCommand.shouldDisplay$1 (/Users/mit/.atom/packages/dartlang/web/entry.dart.js:24527:22)
  at ContextMenuItem_toJs_closure.dart.ContextMenuItem_toJs_closure.call$1 (/Users/mit/.atom/packages/dartlang/web/entry.dart.js:20478:44)
  at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/mit/.atom/packages/dartlang/web/entry.dart.js:17458:28)
  at dart._callDartFunction (/Users/mit/.atom/packages/dartlang/web/entry.dart.js:37998:31)
  at Object.shouldDisplay (/Users/mit/.atom/packages/dartlang/web/entry.dart.js:37986:18)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:108:25)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:166:27)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  2x -0:23.5.0 grammar-selector:show (atom-text-editor.editor)
     -0:15.2.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:12.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "dartlang": {
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.3.14
linter, v1.3.4

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
If people hit this again, we have another issue with parts of an old plugin still being active after an update to a new version. A restart of atom will fix it.
