### ISSUE TITLE
Stack trace in AtomEvent get targetFilePath

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#224]
Clicked on something, not sure what.

TypeError: undefined is not a function
    at J.getAttribute$1$x (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:46228:41)
    at AtomEvent.dart.AtomEvent.get$targetFilePath (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20820:20)
    at PubContextCommand.dart.PubContextCommand.shouldDisplay$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:24639:31)
    at ContextMenuItem_toJs_closure.dart.ContextMenuItem_toJs_closure.call$1 (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:20527:44)
    at dart.Primitives_applyFunctionWithPositionalArguments (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:17501:28)
    at dart._callDartFunction (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:38118:31)
    at Object.shouldDisplay (/Users/skybrian/.atom/packages/dartlang/web/entry.dart.js:38106:18)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:108:25)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:166:27)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)

**Comment by devoncarew** [comment]
fixed in `0.3.16`
