### ISSUE TITLE
Uncaught error after creating new Dart library. Seems related to outline view

### ISSUE THREAD

**Issue by austincummings** [dart-atom/dartlang#274]
Using version 1.12 of the 64-bit Linux Dart SDK.

1. Create a new Dart package with pubspec
2. Create lib directory with file in it
3. Open Dart file in lib and begin typing `library`
4. Outline view does not update with new members

**Atom Version**: 1.0.10
**System**: Ubuntu 15.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.1

### Stack Trace

Uncaught Uncaught Error: NullError: method not found: 'get$iterator' on null
Stack Trace:
TypeError: Cannot read property 'get$iterator' of null
    at [object Object].J.get$iterator$ax (/home/austin/.atom/packages/dartlang/web/entry.dart.js:40600:41)
    at OutlineView.dart.OutlineView._handleOutline$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:23413:23)
    at [object Object].<anonymous> (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16917:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30734:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:29878:20)
    at _DelayedData.dart._DelayedData.perform$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30072:18)
    at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30145:16)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30120:12)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:29023:30)
    at [object Object].dart._microtaskLoop (/home/austin/.atom/packages/dartlang/web/entry.dart.js:27728:12)
    at [object Object].dart._microtaskLoopEntry (/home/austin/.atom/packages/dartlang/web/entry.dart.js:27734:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16100:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:17775:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:15714:25)
    at [object Object].dart._callInIsolate (/home/austin/.atom/packages/dartlang/web/entry.dart.js:15354:28)
    at dart.invokeClosure (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16817:18)

```
At /home/austin/.atom/packages/dartlang/web/entry.dart.js:15723

Uncaught Error: NullError: method not found: 'get$iterator' on null
Stack Trace:
TypeError: Cannot read property 'get$iterator' of null
    at [object Object].J.get$iterator$ax (/home/austin/.atom/packages/dartlang/web/entry.dart.js:40600:41)
    at OutlineView.dart.OutlineView._handleOutline$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:23413:23)
    at [object Object].<anonymous> (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16917:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30734:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:29878:20)
    at _DelayedData.dart._DelayedData.perform$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30072:18)
    at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30145:16)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30120:12)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:29023:30)
    at [object Object].dart._microtaskLoop (/home/austin/.atom/packages/dartlang/web/entry.dart.js:27728:12)
    at [object Object].dart._microtaskLoopEntry (/home/austin/.atom/packages/dartlang/web/entry.dart.js:27734:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16100:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:17775:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:15714:25)
    at [object Object].dart._callInIsolate (/home/austin/.atom/packages/dartlang/web/entry.dart.js:15354:28)
    at dart.invokeClosure (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16817:18)
    at [object Object].dart.wrapException (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16669:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:30703:17)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:29023:30)
    at [object Object].dart._microtaskLoop (/home/austin/.atom/packages/dartlang/web/entry.dart.js:27728:12)
    at [object Object].dart._microtaskLoopEntry (/home/austin/.atom/packages/dartlang/web/entry.dart.js:27734:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16100:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:17775:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/austin/.atom/packages/dartlang/web/entry.dart.js:15714:25)
    at [object Object].dart._callInIsolate (/home/austin/.atom/packages/dartlang/web/entry.dart.js:15354:28)
    at dart.invokeClosure (/home/austin/.atom/packages/dartlang/web/entry.dart.js:16817:18)
    at /home/austin/.atom/packages/dartlang/web/entry.dart.js:16838:18
```

### Commands

```
  3x -0:30.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:00.5.0 dartlang:newline (atom-text-editor.editor.is-focused)
     -0:00.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.3.0 dartlang:newline (atom-text-editor.editor.is-focused)
     -0:00.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/austin/workspace"
  },
  "dartlang": {
    "sdkLocation": "/home/austin/lib/dart-sdk"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.3.0
atom-typescript, v6.0.0
dartlang, v0.4.1
editorconfig, v1.1.1
file-icons, v1.6.9
hex, v0.6.2
highlight-selected, v0.10.1
linter, v1.5.0
minimap, v4.13.2
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0

# Dev
Sublime-Style-Column-Selection, v1.3.0
```

**Comment by austincummings** [comment]
Seems to be when the Dart file doesn't have any members in it yet. Once I add a member to the file it stops throwing the exception.
