### ISSUE TITLE
Uncaught Uncaught Error: NullError: method not found: 'get$iterator' on nullStack Trace:TypeErr...

### ISSUE THREAD

**Issue by 4stern** [dart-atom/dartlang#277]
[Enter steps to reproduce below:]

1. using atom editor (current version 1.0.10) and open a empty dart file
2. focus the file and change it
3. Errors shown

**Atom Version**: 1.0.10
**System**: Ubuntu 14.04.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.1

### Stack Trace

Uncaught Uncaught Error: NullError: method not found: 'get$iterator' on null
Stack Trace:
TypeError: Cannot read property 'get$iterator' of null
    at [object Object].J.get$iterator$ax (/home/robert/.atom/packages/dartlang/web/entry.dart.js:40600:41)
    at OutlineView.dart.OutlineView._handleOutline$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:23413:23)
    at [object Object].<anonymous> (/home/robert/.atom/packages/dartlang/web/entry.dart.js:16917:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30734:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:29878:20)
    at _DelayedData.dart._DelayedData.perform$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30072:18)
    at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30145:16)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30120:12)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:29023:30)
    at [object Object].dart._microtaskLoop (/home/robert/.atom/packages/dartlang/web/entry.dart.js:27728:12)

```
At /home/robert/.atom/packages/dartlang/web/entry.dart.js:15723

Uncaught Error: NullError: method not found: 'get$iterator' on null
Stack Trace:
TypeError: Cannot read property 'get$iterator' of null
    at [object Object].J.get$iterator$ax (/home/robert/.atom/packages/dartlang/web/entry.dart.js:40600:41)
    at OutlineView.dart.OutlineView._handleOutline$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:23413:23)
    at [object Object].<anonymous> (/home/robert/.atom/packages/dartlang/web/entry.dart.js:16917:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30734:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:29878:20)
    at _DelayedData.dart._DelayedData.perform$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30072:18)
    at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30145:16)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30120:12)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:29023:30)
    at [object Object].dart._microtaskLoop (/home/robert/.atom/packages/dartlang/web/entry.dart.js:27728:12)
    at [object Object].dart.wrapException (/home/robert/.atom/packages/dartlang/web/entry.dart.js:16669:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:30703:17)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:29023:30)
    at [object Object].dart._microtaskLoop (/home/robert/.atom/packages/dartlang/web/entry.dart.js:27728:12)
    at [object Object].dart._microtaskLoopEntry (/home/robert/.atom/packages/dartlang/web/entry.dart.js:27734:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:16100:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:17775:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:15714:25)
    at [object Object].dart._callInIsolate (/home/robert/.atom/packages/dartlang/web/entry.dart.js:15354:28)
    at dart.invokeClosure (/home/robert/.atom/packages/dartlang/web/entry.dart.js:16817:18)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "dartlang": {
    "sdkLocation": "/usr/lib/dart"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.4.1
linter, v1.5.0

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-atom/dartlang/pull/275; thanks for the report!
