### ISSUE TITLE
Error thrown when outline view disabled

### ISSUE THREAD

**Issue by rwl** [dart-atom/dartlang#294]
[Enter steps to reproduce below:]

1. Disable "Show outline view" under dartlang package settings
2. Open .dart file, move cursor

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.2

### Stack Trace

Uncaught Uncaught Error: NullError: method not found: 'clear$0' on null
Stack Trace:
TypeError: Cannot read property 'clear$0' of null
  at OutlineView.dart.OutlineView._handleOutline$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:23438:27)
  at [object Object].<anonymous> (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16937:32)
  at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30771:20)
  at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:29915:20)
  at _DelayedData.dart._DelayedData.perform$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30109:18)
  at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30182:16)
  at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30157:12)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:29060:30)
  at [object Object].dart._microtaskLoop (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:27765:12)
  at [object Object].dart._microtaskLoopEntry (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:27771:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16120:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:17795:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:15734:25)
  at [object Object].dart._callInIsolate (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:15374:28)
  at dart.invokeClosure (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16837:18)
  at /home/rwl/.atom/packages/dartlang/web/entry.dart.js:16858:18

```
At /home/rwl/.atom/packages/dartlang/web/entry.dart.js:15743

Uncaught Error: NullError: method not found: 'clear$0' on null
Stack Trace:
TypeError: Cannot read property 'clear$0' of null
  at OutlineView.dart.OutlineView._handleOutline$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:23438:27)
  at [object Object].<anonymous> (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16937:32)
  at _RootZone.dart._RootZone.runUnaryGuarded$2 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30771:20)
  at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:29915:20)
  at _DelayedData.dart._DelayedData.perform$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30109:18)
  at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30182:16)
  at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30157:12)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:29060:30)
  at [object Object].dart._microtaskLoop (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:27765:12)
  at [object Object].dart._microtaskLoopEntry (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:27771:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16120:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:17795:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:15734:25)
  at [object Object].dart._callInIsolate (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:15374:28)
  at dart.invokeClosure (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16837:18)
  at /home/rwl/.atom/packages/dartlang/web/entry.dart.js:16858:18

  at [object Object].dart.wrapException (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16689:17)
  at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:30740:17)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:29060:30)
  at [object Object].dart._microtaskLoop (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:27765:12)
  at [object Object].dart._microtaskLoopEntry (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:27771:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16120:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:17795:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:15734:25)
  at [object Object].dart._callInIsolate (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:15374:28)
  at dart.invokeClosure (/home/rwl/.atom/packages/dartlang/web/entry.dart.js:16837:18)
  at /home/rwl/.atom/packages/dartlang/web/entry.dart.js:16858:18

```

### Commands

```
     -5:40.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -5:35.5.0 settings-view:open (atom-pane.pane.active)
     -5:26.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "language-matlab",
      "word-jumper",
      "linter-dartanalyzer"
    ]
  },
  "dartlang": {
    "sdkLocation": "/usr/lib/dart",
    "formatOnSave": true,
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
build-tools, v3.7.0
dartlang, v0.4.2
language-cmake, v0.1.4
language-docker, v1.1.3
language-matlab-octave, v0.1.1
language-openscad, v0.3.0
language-pascal, v0.7.0
language-protobuf, v0.5.0
last-cursor-position, v0.9.0
linter, v1.5.0

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report! This is fixed but not yet published.
