### ISSUE TITLE
Uncaught Uncaught Error: NullError: method not found: 'nodes' on null Stack Trace: TypeError: Cannot read property 'nodes' of null at OutlineView.dart.OutlineView._cursorChanged$1 

### ISSUE THREAD

**Issue by iposva-google** [dart-atom/dartlang#307]
1. Errors popped up in the side bar.
2. Copy & pasted error report 

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.3

### Stack Trace

Uncaught Uncaught Error: NullError: method not found: 'nodes' on null
Stack Trace:
TypeError: Cannot read property 'nodes' of null
  at OutlineView.dart.OutlineView._cursorChanged$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:23454:35)
  at [object Object].<anonymous> (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16937:32)
  at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30771:20)
  at _ForwardingStreamSubscription.dart._BufferingStreamSubscription._sendData$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29915:20)
  at _ForwardingStreamSubscription.dart._BufferingStreamSubscription._async$_add$1 [as super$_BufferingStreamSubscription$_add] (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29865:16)
  at _ForwardingStreamSubscription.dart._ForwardingStreamSubscription._async$_add$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30436:14)
  at _MapStream.dart._MapStream._handleData$2 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30532:14)
  at _ForwardingStreamSubscription.dart._ForwardingStreamSubscription._handleData$1.H.computeSignature.func [as _handleData$1] (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30464:22)
  at [object Object].<anonymous> (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16937:32)
  at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30771:20)
  at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29915:20)
  at _DelayedData.dart._DelayedData.perform$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30109:18)
  at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30182:16)
  at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30157:12)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29060:30)
  at [object Object].dart._microtaskLoop (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:27765:12)
  at [object Object].dart._microtaskLoopEntry (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:27771:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16120:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:17795:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15734:25)
  at [object Object].dart._callInIsolate (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15374:28)
  at dart.invokeClosure (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16837:18)
  at /Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16858:18

```
At /Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15743

Uncaught Error: NullError: method not found: 'nodes' on null
Stack Trace:
TypeError: Cannot read property 'nodes' of null
  at OutlineView.dart.OutlineView._cursorChanged$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:23454:35)
  at [object Object].<anonymous> (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16937:32)
  at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30771:20)
  at _ForwardingStreamSubscription.dart._BufferingStreamSubscription._sendData$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29915:20)
  at _ForwardingStreamSubscription.dart._BufferingStreamSubscription._async$_add$1 [as super$_BufferingStreamSubscription$_add] (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29865:16)
  at _ForwardingStreamSubscription.dart._ForwardingStreamSubscription._async$_add$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30436:14)
  at _MapStream.dart._MapStream._handleData$2 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30532:14)
  at _ForwardingStreamSubscription.dart._ForwardingStreamSubscription._handleData$1.H.computeSignature.func [as _handleData$1] (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30464:22)
  at [object Object].<anonymous> (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16937:32)
  at _RootZone.dart._RootZone.runUnaryGuarded$2 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30771:20)
  at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29915:20)
  at _DelayedData.dart._DelayedData.perform$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30109:18)
  at _StreamImplEvents.dart._StreamImplEvents.handleNext$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30182:16)
  at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30157:12)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29060:30)
  at [object Object].dart._microtaskLoop (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:27765:12)
  at [object Object].dart._microtaskLoopEntry (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:27771:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16120:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:17795:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15734:25)
  at [object Object].dart._callInIsolate (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15374:28)
  at dart.invokeClosure (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16837:18)
  at /Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16858:18

  at [object Object].dart.wrapException (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16689:17)
  at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:30740:17)
  at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:29060:30)
  at [object Object].dart._microtaskLoop (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:27765:12)
  at [object Object].dart._microtaskLoopEntry (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:27771:11)
  at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16120:35)
  at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:17795:41)
  at _IsolateContext.dart._IsolateContext.eval$1 (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15734:25)
  at [object Object].dart._callInIsolate (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:15374:28)
  at dart.invokeClosure (/Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16837:18)
  at /Users/iposva/.atom/packages/dartlang/web/entry.dart.js:16858:18

```

### Commands

```
     -8:56.9.0 dartlang:analysis-server-status (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -8:41.4.0 dartlang:reanalyze-sources (atom-text-editor.editor.is-focused)
     -3:17.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:33.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:59.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:53.7.0 dartlang:reanalyze-sources (atom-text-editor.editor.is-focused)
     -1:41.8.0 dartlang:analysis-server-status (atom-text-editor.editor.is-focused)
  2x -1:26 dartlang:reanalyze-sources (atom-text-editor.editor.is-focused)
     -0:18.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.7.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "dartlang",
      "linter"
    ]
  },
  "dartlang": {
    "sdkLocation": "/Users/iposva/bin/dart-sdk",
    "useErrorsView": false,
    "showInfos": false,
    "showTodos": false,
    "filterUnnamedLibraryWarnings": false,
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.4.3
linter, v1.5.1

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for this report (and #309). Both issues existed in `0.4.2` and were fixed in `0.4.3`.

I think you're hitting https://github.com/dart-atom/dartlang/issues/240. Some other code is still active after a plugin upgrade. I'm not quite sure how to tackle that issue yet. Re-starting Atom should solve the issues for you in the meantime.

I'll close these issues in favor of https://github.com/dart-atom/dartlang/issues/240.
