### ISSUE TITLE
Error when activating plugin

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#37]
![screen shot 2015-07-09 at 4 40 38 pm](https://cloud.githubusercontent.com/assets/5479/8609378/4399e48c-2659-11e5-8d4c-a2e36e00dd71.png)

Stack trace:

```
Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at new HandleWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
    at new PathWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
    at Object.exports.watch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
    at Directory.module.exports.Directory.subscribeToNativeChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:334:109)
    at Directory.module.exports.Directory.willAddSubscription (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:95:14)
    at Directory.willAddSubscription (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:3:61)
    at Directory.module.exports.Directory.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:89:12)
    at JsObject.dart.JsObject.callMethod$2 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:26052:44)

```

On version 0.2.2.

**Comment by devoncarew** [comment]
Do you have a sense of which project it had trouble watching? We watch the main directory of each project, listening to see if a `pubspec.yaml` or `.packages` file is created or deleted.

**Comment by sethladd** [comment]
I believe I was trying to open the main Dart SDK.

I'll keep a better eye on this and let you know if I notice a pattern.
