### ISSUE TITLE
Uncaught Uncaught Error: Error: Unable to watch pathStack Trace:Error: Unable to watch path   ...

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-atom/dartlang#39]
Launch atom (right after upgrading from previosu version of atom and installing dartlang)
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.2.2

### Stack Trace

Uncaught Uncaught Error: Error: Unable to watch path
Stack Trace:
Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at new HandleWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
    at new PathWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
    at Object.exports.watch (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
    at Directory.module.exports.Directory.subscribeToNativeChangeEvents (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:334:109)
    at Directory.module.exports.Directory.willAddSubscription (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:95:14)
    at Directory.willAddSubscription (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:3:61)
    at Directory.module.exports.Directory.onDidChange (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:89:12)
    at JsObject.dart.JsObject.callMethod$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:26052:44)

```
At /usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:11309

Uncaught Error: Error: Unable to watch path
Stack Trace:
Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at new HandleWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
    at new PathWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
    at Object.exports.watch (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
    at Directory.module.exports.Directory.subscribeToNativeChangeEvents (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:334:109)
    at Directory.module.exports.Directory.willAddSubscription (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:95:14)
    at Directory.willAddSubscription (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:3:61)
    at Directory.module.exports.Directory.onDidChange (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:89:12)
    at JsObject.dart.JsObject.callMethod$2 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:26052:44)
    at dart.wrapException (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:12149:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:21783:17)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:20321:30)
    at dart._microtaskLoop (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:19081:12)
    at dart._microtaskLoopEntry (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:19087:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:11655:35)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:13146:41)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:11300:25)
    at dart._callInIsolate (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:10931:28)
    at dart.invokeClosure (/usr/local/google/home/eseidel/.atom/packages/dartlang/web/entry.dart.js:12284:18)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
dartlang, v0.2.2

# Dev
No dev packages
```

**Comment by eseidelGoogle** [comment]
I think it may have been confused by trying to open atom:config, since that was the window I last had open at quit.

**Comment by devoncarew** [comment]
Related to #37; thanks for the report and the `atom:config` details - I'll take a look.
