### ISSUE TITLE
Uncaught TypeError: Cannot read property 'execBinSimple$2' of null

### ISSUE THREAD

**Issue by ianloic** [dart-atom/dartlang#403]
1. Installed Atom & dartlang & linter
2. Packages > Dart > Create new Flutter project...
3. *boom*

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'execBinSimple$2' of null

```
At /Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:27856

TypeError: Cannot read property 'execBinSimple$2' of null
    at PubApp.dart.PubApp.isInstalled$0 (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:27856:92)
    at CreateProjectManager.dart.CreateProjectManager._createProject$1 (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:25095:22)
    at [object Object].<anonymous> (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:18226:32)
    at CommandRegistry_add_closure.dart.CommandRegistry_add_closure.call$1 (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:20030:35)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:17902:28)
    at dart._callDartFunction (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:40492:31)
    at atom-workspace.<anonymous> (/Users/ianloic/.atom/packages/dartlang/web/entry.dart.js:40480:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
```

### Commands

```
     -0:00.6.0 dartlang:create-flutter-project (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.4.9
linter, v1.8.1

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report! It looks like we're not able to find your Dart sdk. I'll update to provide a check and a better error message. You can point the plugin to your sdk from the `dartlang` settings page, in the `Dart SDK Location` field.
