### ISSUE TITLE
Traceback for skytools and python subprocces.py(Atom Editor on Ubuntu)

### ISSUE THREAD

**Issue by ComsGen** [dart-atom/dartlang#404]
```
Traceback (most recent call last):
  File "packages/sky/sky_tool", line 1320, in <module>
    sys.exit(SkyShellRunner().main())
  File "packages/sky/sky_tool", line 1311, in main
    exit_code = args.func(args, pids)
  File "packages/sky/sky_tool", line 266, in run
    started_sky_on_android = android.setup_servers(sky_server_root, main_dart, pids, args)
  File "packages/sky/sky_tool", line 496, in setup_servers
    sky_server_pid = _start_http_server(sky_server_port, sky_server_root)
  File "packages/sky/sky_tool", line 80, in _start_http_server
    return subprocess.Popen(server_command, cwd=root).pid
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I don't understand this

**Comment by devoncarew** [comment]
@ComsGen, thanks for the report. At this point, the python deploy script is deprecated; we've switched over to a re-written dart version. The latest atom plugin uses this re-written script. Can you re-try with the latest?
