### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith$1' of undefined

### ISSUE THREAD

**Issue by lukechurch** [dart-atom/dartlang#458]
@devoncarew This happened once after upgrading the plugin. After restarting, it doesn't appear to to repeat, and I don't know what version I was on before I think it was 2 versions back.

I'm not sure there's much more info I can give you, sorry. Sending this more as an FYi. If it isn't useful, feel free to close the issue.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.12

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith$1' of undefined

```
At /Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:21255

TypeError: Cannot read property 'endsWith$1' of undefined
    at [object Object].J.endsWith$1$s (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:58779:40)
    at BufferObserverManager__closure.dart.BufferObserverManager__closure.call$1 (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:27923:15)
    at Workspace_observeTextEditors_closure.dart.Workspace_observeTextEditors_closure.call$1 (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:24401:48)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:22226:28)
    at dart._callDartFunction (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:49341:31)
    at /Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:49602:20
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
    at JsObject.dart.JsObject.callMethod$2 (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:49452:44)
    at Workspace.dart.ProxyHolder.invoke$4 (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:31317:23)
    at Workspace.dart.ProxyHolder.invoke$2 (/Users/lukechurch/.atom/packages/dartlang/web/entry.dart.js:31326:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "dartlang": {
    "sdkLocation": "/Users/lukechurch/homebrew/Cellar/dart/1.12.1/libexec",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.4.12
linter, v1.9.1

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks! It was a real issue - an NPE in some new code to help manage when there are multiple editors open on the same file.

**Comment by nalkon** [comment]
How can I get the fix?

**Comment by devoncarew** [comment]
This fix has made its way into the current release - you should have it already.

**Comment by devoncarew** [comment]
in plugin version `0.4.13`

**Comment by nalkon** [comment]
I have version 0.4.13 and still have the problem.

Atom version: 1.1.0
OS: Ubuntu 14.04

Please let me know if you need additional information.

**Comment by devoncarew** [comment]
Can you try re-starting Atom? And if you see the problem again, can you provide a stack trace? Thanks!

**Comment by nalkon** [comment]
Restarted Atom. The problem is still there. Here is stack trace. I noticed now that the exception is thrown from a different place.

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.13


### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith$1' of undefined

```
At /home/nd/.atom/packages/dartlang/web/entry.dart.js:55915

TypeError: Cannot read property 'endsWith$1' of undefined
  at [object Object].J.endsWith$1$s (/home/nd/.atom/packages/dartlang/web/entry.dart.js:55915:40)
  at CliLaunchType.dart.CliLaunchType.canLaunch$1 (/home/nd/.atom/packages/dartlang/web/entry.dart.js:30733:16)
  at LaunchManager.dart.LaunchManager.getHandlerFor$1 (/home/nd/.atom/packages/dartlang/web/entry.dart.js:30439:20)
  at RunApplicationManager.dart.RunApplicationManager._handleFastRunCommand$1 (/home/nd/.atom/packages/dartlang/web/entry.dart.js:34390:90)
  at RunApplicationManager_closure0.dart.RunApplicationManager_closure0.call$1 (/home/nd/.atom/packages/dartlang/web/entry.dart.js:34470:36)
  at CommandRegistry_add_closure.dart.CommandRegistry_add_closure.call$1 (/home/nd/.atom/packages/dartlang/web/entry.dart.js:23293:35)
  at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/home/nd/.atom/packages/dartlang/web/entry.dart.js:21056:28)
  at dart._callDartFunction (/home/nd/.atom/packages/dartlang/web/entry.dart.js:47247:31)
  at HTMLOListElement.<anonymous> (/home/nd/.atom/packages/dartlang/web/entry.dart.js:47508:20)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -0:06.5.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 dartlang:run-application (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "dartlang": {
    "sdkLocation": "/usr/lib/dart"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.4.13
linter, v1.10.0

# Dev
No dev packages

**Comment by devoncarew** [comment]
Thanks! I'll investigate.
