### ISSUE TITLE
Uncaught TypeError: Cannot read property 'execBin$3$cwd' of null

### ISSUE THREAD

**Issue by loganfreeman** [dart-atom/dartlang#497]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.13

### Stack Trace

Uncaught TypeError: Cannot read property 'execBin$3$cwd' of null

```
At /Users/scheng/.atom/packages/dartlang/web/entry.dart.js:33506

TypeError: Cannot read property 'execBin$3$cwd' of null
    at PubJob.dart.PubJob.run$0 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:33506:128)
    at JobManager.dart.JobManager._exec$1 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:30068:13)
    at JobManager.dart.JobManager._checkForRunnableJobs$0 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:30049:20)
    at JobManager.dart.JobManager.schedule$1 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:30023:14)
    at PubManager__showRunPubDialog_closure.dart.PubManager__showRunPubDialog_closure.call$0 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:33269:74)
    at NotificationButton.dart.NotificationButton.onDidClick$0 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:23416:32)
    at NotificationButton_toProxy_closure.dart.NotificationButton_toProxy_closure.call$1 (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:23422:44)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:21056:28)
    at dart._callDartFunction (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:47247:31)
    at HTMLAnchorElement.<anonymous> (/Users/scheng/.atom/packages/dartlang/web/entry.dart.js:47508:20)
```

### Commands

```
     -0:15 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, vundefined
atom-typescript, v7.7.2
dartlang, v0.4.13
language-groovy, v0.4.0
linter, v1.10.0
seti-ui, vundefined
standard-formatter, v1.2.0

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report! I'll add a guard for this.

This will occur when there's no Dart SDK configured. You can configure this through the settings for the dart plugin (Atom > Preferences > Settings > dartlang), or run the `'auto locate sdk'` command from atom's command palette. You will need a Dart sdk installed for these commands to work :)
