### ISSUE TITLE
Uncaught TypeError: Cannot read property '_executables' of null

### ISSUE THREAD

**Issue by mauricioms** [dart-atom/dartlang#533]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Linux Mint
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.15

### Stack Trace

Uncaught TypeError: Cannot read property '_executables' of null

```
At /home/mauricio/.atom/packages/dartlang/web/entry.dart.js:24843

TypeError: Cannot read property '_executables' of null
    at AnalysisServer.dart.AnalysisServer.isExecutable$1 (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:24843:28)
    at CliLaunchType.dart.CliLaunchType.canLaunch$1 (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:32154:87)
    at LaunchManager.dart.LaunchManager.getHandlerFor$1 (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:31759:20)
    at RunAppContextCommand.dart.RunAppContextCommand.shouldDisplay$1 (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:36034:84)
    at ContextMenuItem_toJs_closure.dart.ContextMenuItem_toJs_closure.call$1 (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:24025:44)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:21710:28)
    at dart._callDartFunction (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:48961:31)
    at Object.shouldDisplay (/home/mauricio/.atom/packages/dartlang/web/entry.dart.js:49222:20)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:94:25)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:152:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "/usr/bin/dart",
    "showTodos": true,
    "formatOnSave": true,
    "noPackageSymlinks": true,
    "debugAnalysisServer": true
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
color-picker, v2.0.13
dartlang, v0.4.15
jsformat, v0.9.0
linter, v1.11.2

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report! Fixed in https://github.com/dart-atom/dartlang/pull/537.
