### ISSUE TITLE
Failed to activate the dartlang package

### ISSUE THREAD

**Issue by 7thsky** [dart-atom/dartlang#545]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.15

### Stack Trace

Failed to activate the dartlang package

```
At Invalid argument: Instance of 'JsObject'

Invalid argument: Instance of 'JsObject'
    at [object Object].dart.wrapException (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:21791:17)
    at [object Object].dart._parseJson (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:42774:17)
    at JsonCodec.dart.JsonCodec.decode$2$reviver (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:43255:18)
    at JsonCodec.dart.JsonCodec.decode$1 (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:43258:21)
    at State.dart.State.registerStorable$2 (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:36598:79)
    at AtomDartPackage.packageActivated$1 (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:33787:12)
    at [object Object].<anonymous> (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:22039:32)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:21710:28)
    at dart._callDartFunction (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:48961:31)
    at Object.activate (/Users/marat/.atom/packages/dartlang/web/entry.dart.js:49222:20)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "seti-monokai"
    ],
    "disabledPackages": [
      "dart-tools"
    ],
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-material-ui, v0.8.0
atom-typescript, v7.11.1
dartlang, v0.4.15
language-brightscript, v0.0.0
linter, v1.11.2
seti-monokai, v0.3.1

# Dev
No dev packages
```

**Comment by 4stern** [comment]
Since a few days i have this issue too!

Atom Version: 1.2.4
System: Mac Ubuntu 14.04
Thrown From: dartlang package, v0.4.15

### Stack Trace
```
Invalid argument: Instance of 'JsObject'
    at [object Object].dart.wrapException (/home/robert/.atom/packages/dartlang/web/entry.dart.js:21791:17)
    at [object Object].dart._parseJson (/home/robert/.atom/packages/dartlang/web/entry.dart.js:42774:17)
    at JsonCodec.dart.JsonCodec.decode$2$reviver (/home/robert/.atom/packages/dartlang/web/entry.dart.js:43255:18)
    at JsonCodec.dart.JsonCodec.decode$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:43258:21)
    at State.dart.State.registerStorable$2 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:36598:79)
    at AtomDartPackage.packageActivated$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:33787:12)
    at [object Object].<anonymous> (/home/robert/.atom/packages/dartlang/web/entry.dart.js:22039:32)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/home/robert/.atom/packages/dartlang/web/entry.dart.js:21710:28)
    at dart._callDartFunction (/home/robert/.atom/packages/dartlang/web/entry.dart.js:48961:31)
    at Object.activate (/home/robert/.atom/packages/dartlang/web/entry.dart.js:49222:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:333:19
    at /usr/share/atom/resources/app.asar/src/config.js:588:20
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:773:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:565:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:226:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:343:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Installed Packages
atom-typescript 7.12.1
dartlang 0.4.15
gulp-controll 0.4.3
linter 1.11.2

**Comment by devoncarew** [comment]
The fix for this is in master but we haven't yet published a version with the fix. The next version will probably go out monday/tuesday. You may be able to work around it temporarily by deleting/renaming your `~/.atom/storage/` directory.
