### ISSUE TITLE
Uncaught NullError: method not found: 'invoke$1' on null

### ISSUE THREAD

**Issue by shieldwed** [dart-atom/dartlang#611]
1. Remove Dart project folder from the projects panel.

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.16

### Stack Trace

Uncaught NullError: method not found: 'invoke$1' on null

```
At C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:21314

TypeError: Cannot read property 'invoke$1' of null
    at ProxyHolder_eventStream_closure.dart.ProxyHolder_eventStream_closure.call$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:31827:38)
    at [object Object].dart._runGuarded (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:39406:38)
    at _AsyncBroadcastStreamController.dart._BroadcastStreamController._callOnCancel$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:39802:11)
    at _AsyncBroadcastStreamController.dart._BroadcastStreamController._recordCancel$1 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:39713:18)
    at _BroadcastSubscription.dart._ControllerSubscription._onCancel$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:40965:46)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._cancel$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:41046:35)
    at _BroadcastSubscription.dart._BufferingStreamSubscription.cancel$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:41030:14)
    at _ProjectConfigurations.dart._ProjectConfigurations.dispose$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:32786:35)
    at LaunchConfigurationManager.dart.LaunchConfigurationManager._handleProjectRemoved$1 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:32632:18)
    at [object Object].<anonymous> (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:22584:32)
    at _RootZone.dart._RootZone.runUnaryGuarded$2 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:41676:20)
    at _BroadcastSubscription.dart._BufferingStreamSubscription._sendData$1 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:41103:20)
    at _DelayedData.dart._DelayedData.perform$1 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:41249:18)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:41302:16)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:40519:30)
    at [object Object].dart._microtaskLoop (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:39342:12)
    at [object Object].dart._microtaskLoopEntry (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:39348:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:21664:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:23504:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:21305:25)
    at [object Object].dart._callInIsolate (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:20949:28)
    at dart.invokeClosure (C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:22484:18)
    at C:\Users\shiel\.atom\packages\dartlang\web\entry.dart.js:22505:18
```

### Commands

```
     -1:41.1.0 dartlang:debug-run (atom-text-editor.editor)
     -1:41.1.0 dartlang:run-application (atom-text-editor.editor)
     -1:01.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:56.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:55.9.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:52.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:51 core:save (atom-text-editor.editor.is-focused)
     -0:47.4.0 dartlang:debug-run (atom-text-editor.editor.is-focused)
     -0:47.4.0 dartlang:run-application (atom-text-editor.editor.is-focused)
     -0:31.2.0 dartlang:debug-run (atom-text-editor.editor.is-focused)
     -0:31.2.0 dartlang:run-application (atom-text-editor.editor.is-focused)
     -0:26.5.0 dartlang:debug-run (atom-text-editor.editor.is-focused)
     -0:26.5.0 dartlang:run-application (atom-text-editor.editor.is-focused)
  4x -0:15.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:09.9.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -0:03.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "D:\\Programs\\commonfiles\\dart-sdk"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.10.3
atom-yeoman, v0.3.15
autocomplete-python, v1.0.3
dartlang, v0.4.16
json-schema, v0.1.15
language-groovy, v0.4.0
language-ini, v1.14.0
language-prolog, v0.10.0
language-puppet, v0.15.0
language-scheme, v1.4.0
language-systemd, v0.1.0
linter, v1.11.3
omnisharp-atom, v0.26.1
pigments, v0.19.1

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report!

**Comment by shieldwed** [comment]
Sorry, forgot to fill in the action I did before it crashed. Just edited the comment to include it (see above).
