### ISSUE TITLE
Uncaught -32602: Invalid params

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#624]
[Enter steps to reproduce below:]

1. set breakpoint with F9
2. hit F9 again

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.17

### Stack Trace

Uncaught -32602: Invalid params

```
At /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:21314

-32602: Invalid params
    at [object Object].dart.wrapException (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22336:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:41645:19)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:40519:30)
    at [object Object].dart._microtaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:39342:12)
    at [object Object].dart._microtaskLoopEntry (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:39348:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:21664:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23504:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:21305:25)
    at [object Object].dart._callInIsolate (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:20949:28)
    at dart.invokeClosure (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22484:18)
    at /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22505:18
```

### Commands

```
     -5:33.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -4:54.2.0 core:close (div.panels-item)
  3x -4:00.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:55.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:52.9.0 dartlang:run-application (atom-text-editor.editor.is-focused)
     -3:06.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:04.8.0 core:save (atom-text-editor.editor.is-focused)
     -3:03.3.0 core:close (atom-text-editor.editor.is-focused)
     -3:01.9.0 dartlang:run-application (atom-text-editor.editor.is-focused)
  3x -0:19.9.0 dartlang:debug-toggle-breakpoint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dart-tools"
    ]
  },
  "dartlang": {
    "sdkLocation": "/Users/sethladd/homebrew/opt/dart/libexec",
    "showOutlineView": false,
    "flutterSdkLocation": "/Users/sethladd/Code/flutter"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.4.17
highlight-selected, v0.11.1
last-cursor-position, v0.9.0
linter, v1.11.3
minimap, v4.16.2

# Dev
No dev packages
```

**Comment by sethladd** [comment]
Seems repeatable, put cursor on line, hit F9, then hit F9 again.

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/pull/651
