### ISSUE TITLE
Cannot Debug @dart-atom0.4.17 @atom1.3.1

### ISSUE THREAD

**Issue by tain335** [dart-atom/dartlang#638]
/home/paul/.atom/packages/dartlang/web/entry.dart.js:29625
Hide Stack Trace

```
TypeError: Cannot read property 'catchError$1' of null
    at DebugManager.dart.DebugManager._handleDebugRun$0 (/home/paul/.atom/packages/dartlang/web/entry.dart.js:29625:13)
    at [object Object].<anonymous> (/home/paul/.atom/packages/dartlang/web/entry.dart.js:23298:32)
    at DebugManager__closure.dart.DebugManager__closure.call$1 (/home/paul/.atom/packages/dartlang/web/entry.dart.js:29672:22)
    at CommandRegistry_add_closure.dart.CommandRegistry_add_closure.call$1 (/home/paul/.atom/packages/dartlang/web/entry.dart.js:25256:23)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/home/paul/.atom/packages/dartlang/web/entry.dart.js:22975:28)
    at dart._callDartFunction (/home/paul/.atom/packages/dartlang/web/entry.dart.js:51504:31)
    at atom-workspace.<anonymous> (/home/paul/.atom/packages/dartlang/web/entry.dart.js:51775:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by devoncarew** [comment]
Thanks for the report!

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-atom/dartlang/pull/640.
