### ISSUE TITLE
Uncaught analysis server not available

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#653]
[Enter steps to reproduce below:]

1. showed up shortly after running an app, for the first time after I restarted Atom
2. 

**Atom Version**: 1.3.1
**System**: Mac OS X 10.10.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.5.0

### Stack Trace

Uncaught analysis server not available

```
At /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22424

analysis server not available
    at [object Object].dart.wrapException (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23473:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:44218:19)
    at [object Object].dart._microtaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:41894:27)
    at [object Object].dart._startMicrotaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:41900:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22788:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:24641:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22415:25)
    at [object Object].dart._callInIsolate (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22059:28)
    at dart.invokeClosure (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23621:18)
    at /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23642:18
```

### Commands

```
     -0:30.8.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:11.6.0 dartlang:run-application (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dart-tools"
    ]
  },
  "dartlang": {
    "sdkLocation": "/Users/sethladd/homebrew/opt/dart/libexecXXX",
    "showOutlineView": false,
    "flutterSdkLocation": "/Users/sethladd/Code/flutter"
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.5.0
highlight-selected, v0.11.1
last-cursor-position, v0.9.0
linter, v1.11.3
minimap, v4.18.0

# Dev
No dev packages
```

**Comment by sethladd** [comment]
More graceful error if the SDK directory is not set correctly?
