### ISSUE TITLE
Uncaught TypeError: Cannot read property 'append$1' of null

### ISSUE THREAD

**Issue by Arcrammer** [dart-atom/dartlang#718]
As soon as I try enabling the package I get this error.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'append$1' of null

```
At /Users/alexander/.atom/packages/dartlang/web/entry.dart.js:22641

TypeError: Cannot read property 'append$1' of null
    at [object Object].J.append$1$x (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:63765:40)
    at OutlineView.dart.OutlineView._outline$_install$0 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:36778:11)
    at OutlineView.dart.OutlineView.OutlineView$2 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:37009:16)
    at [object Object].dart.OutlineView.static.OutlineView$ (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:37015:14)
    at OutlineController.dart.OutlineController._handleEditor$1 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:36670:27)
    at [object Object].<anonymous> (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:23941:32)
    at Workspace_observeTextEditors_closure.dart.Workspace_observeTextEditors_closure.call$1 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:25863:30)
    at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:23612:28)
    at dart._callDartFunction (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:53597:31)
    at /Users/alexander/.atom/packages/dartlang/web/entry.dart.js:53882:20
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:288:9)
    at JsObject.dart.JsObject.callMethod$2 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:53711:44)
    at Workspace.dart.ProxyHolder.invoke$4 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:33954:23)
    at Workspace.dart.ProxyHolder.invoke$2 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:33963:21)
    at Workspace.dart.Workspace.observeTextEditors$1 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:25826:40)
    at OutlineController_closure1.dart.OutlineController_closure1.call$0 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:36721:67)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:23008:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:24873:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:22632:25)
    at [object Object].dart._callInIsolate (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:22274:28)
    at dart.invokeClosure (/Users/alexander/.atom/packages/dartlang/web/entry.dart.js:23841:20)
    at /Users/alexander/.atom/packages/dartlang/web/entry.dart.js:23862:18
```

### Commands

```
     -1:15.6.0 core:close (input.hidden-input)
     -0:43.3.0 core:save (input.hidden-input)
     -0:37.1.0 grammar-selector:show (atom-text-editor.editor.editor-colors)
     -0:35.1.0 settings-view:open (input.hidden-input)
     -0:32.7.0 window:toggle-full-screen (input.hidden-input)
     -0:06.7.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-html",
      "synced-sidebar"
    ],
    "followSymlinks": false,
    "projectHome": "~/Sites"
  },
  "dartlang": {
    "sdkLocation": "/usr/local/opt/dart/libexec"
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autocomplete-php, v0.3.7
autocomplete-ruby, v0.1.0
dartlang, v0.5.3
docblockr, v0.7.3
flutter, v0.1.2
language-apache, v1.4.0
language-blade, v0.20.0
language-python-django-templates, v0.1.0
language-scala, v1.1.4
language-shellscript, v0.21.0
language-swift, v0.4.0
linter, v1.11.3
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Hmm, looks like this is only possible if the editor's `shadowRoot` is null. Not sure why this would be happening. This is when we install the outline view into an editor.

**Comment by Arcrammer** [comment]
Note: The package works normally but I am given this message every time I enable it.
