### ISSUE TITLE
dartlang plugin crashes on startup

### ISSUE THREAD

**Issue by abarth** [dart-atom/dartlang#752]
**Atom Version**: 1.0.0
**System**: Ubuntu 14.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.5.4

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:22876

TypeError: Cannot read property 'apply' of undefined
    at JsObject.dart.JsObject.callMethod$2 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:54490:43)
    at JsObject.dart.JsObject.callMethod$1 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:54493:21)
    at ProjectManager.dart.ProjectManager._findDartProjects$2 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:38078:33)
    at ProjectManager.dart.ProjectManager._fullScanForProjects$0 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:38026:38)
    at ProjectManager_closure.dart.ProjectManager_closure.call$0 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:38164:12)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:23255:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:25120:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:22867:25)
    at dart._callInIsolate (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:22509:28)
    at dart.invokeClosure (/usr/local/google/home/abarth/.atom/packages/dartlang/web/entry.dart.js:24088:20)
```

### Commands

```
     -0:04.7.0 dartlang:newline (atom-text-editor.editor.is-focused)
     -0:04.7.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "/src/flutter/engine/src/third_party/dart-sdk/dart-sdk",
    "showTodos": false,
    "showOutlineView": false,
    "enableSuperMixins": true
  }
}
```

### Installed Packages

```coffee
# User
dartlang, v0.5.4
flutter, v0.1.2
language-diff, v0.4.0
linter, v1.11.3
spell-check, v0.66.0
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
It looks like this is due to a recent change - calling the node `homedir()` call. Working on the mac. I can guard against errors from this call.

**Comment by devoncarew** [comment]
@abarth, can you upgrade to `0.5.6` (the latest) and see if you still see the crash? If so, I'll remove the code using `homedir`.

**Comment by abarth** [comment]
Yay, crash is fixed.
