### ISSUE TITLE
Uncaught [RequestError The null object does not have a method 'indexOf'.NoSuchMethodError: meth...

### ISSUE THREAD

**Issue by apwilson** [dart-atom/dartlang#794]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.1

### Stack Trace

Uncaught [RequestError The null object does not have a method 'indexOf'.

NoSuchMethodError: method not found: 'indexOf'
Receiver: null
Arguments: ["."]]

```
At <redacted>/.atom/packages/dartlang/web/entry.dart.js:23262

[RequestError The null object does not have a method 'indexOf'.

NoSuchMethodError: method not found: 'indexOf'
Receiver: null
Arguments: ["."]]
    at [object Object].dart.wrapException (<redacted>/.atom/packages/dartlang/web/entry.dart.js:24326:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (<redacted>/.atom/packages/dartlang/web/entry.dart.js:46129:19)
    at [object Object].dart._microtaskLoop (<redacted>/.atom/packages/dartlang/web/entry.dart.js:43534:27)
    at [object Object].dart._startMicrotaskLoop (<redacted>/.atom/packages/dartlang/web/entry.dart.js:43540:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (<redacted>/.atom/packages/dartlang/web/entry.dart.js:23641:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (<redacted>/.atom/packages/dartlang/web/entry.dart.js:25529:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (<redacted>/.atom/packages/dartlang/web/entry.dart.js:23253:25)
    at [object Object].dart._callInIsolate (<redacted>/.atom/packages/dartlang/web/entry.dart.js:22895:28)
    at dart.invokeClosure (<redacted>/.atom/packages/dartlang/web/entry.dart.js:24474:20)
    at <redacted>/.atom/packages/dartlang/web/entry.dart.js:24495:18
```

### Commands

```
     -0:13 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:12.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "<redacted>",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.2
dartlang, v0.6.1
flutter, v0.2.0
last-cursor-position, v0.9.0
linter, v1.11.3
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by apwilson** [comment]
I've redacted parts of the paths.  See this issue: https://github.com/dart-atom/dartlang/issues/795

**Comment by devoncarew** [comment]
Closing - the issue was a newer atom talking to an older version of flutter.
