### ISSUE TITLE
Reanalyze Sources generates Red error

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#80]
![screen shot 2015-07-17 at 9 57 06 am](https://cloud.githubusercontent.com/assets/5479/8752633/3b047d3e-2c6a-11e5-823e-000f719a3965.png)

```
Uncaught Uncaught Error: Error: This socket has been ended by the other party Stack Trace: Error: This socket has been ended by the other party at Socket.writeAfterFIN [as write] (net.js:275:12) at JsObject.dart.JsObject.callMethod$2 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:27137:44) at 
_AnalysisServerWrappermessageWriter_closure.dart._AnalysisServerWrappermessageWriter_closure.call$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:16143:14) at 
_AnalysisServerWrapper.dart.Server._writeMessage$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:14610:35) at 
_AnalysisServerWrapper.dart.Server._call$2 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:14581:14) at 
AnalysisServer.dart.AnalysisServer.reanalyzeSources$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:15687:21) at 
AtomDartPackage_packageActivatedclosure0.dart.AtomDartPackage_packageActivatedclosure0.call$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:17494:70) at 
_RootZone.dart._RootZone.runUnary$2 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:22737:20) at 
_FuturepropagateToListeners_handleValueCallback.dart._FuturepropagateToListeners_handleValueCallback.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:20862:80) at 
dart._Future.static._Future__propagateToListeners (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:20769:143)
```

(also, line breaks are lost in the red pop up display)

**Comment by sethladd** [comment]
![screen shot 2015-07-17 at 9 58 51 am](https://cloud.githubusercontent.com/assets/5479/8752653/70e0086a-2c6a-11e5-97d5-0cf2ef131ed1.png)

**Comment by devoncarew** [comment]
Can you re-test with the latest?

**Comment by sethladd** [comment]
Just tried it. No red (yay!) but I saw two analysis gears (??)

![screen shot 2015-07-18 at 8 57 03 am](https://cloud.githubusercontent.com/assets/5479/8762329/03e9b8b6-2d2b-11e5-9212-244f500805dd.png)

**Comment by sethladd** [comment]
I'll reopen if I see this again. Thanks for the help!

**Comment by devoncarew** [comment]
Filed an issue for the two analysis gears: https://github.com/dart-atom/dartlang/issues/85
