### ISSUE TITLE
Uncaught RangeError (index): Index out of range: index must not be negative: -2

### ISSUE THREAD

**Issue by jimbeveridge** [dart-atom/dartlang#805]
[Enter steps to reproduce below:]

(I have no idea what I did to cause this.)

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.1
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.2

### Stack Trace

Uncaught RangeError (index): Index out of range: index must not be negative: -2

```
At /usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23569

RangeError (index): Index out of range: index must not be negative: -2
    at [object Object].dart.wrapException (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24633:17)
    at [object Object].dart.ioore (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24586:15)
    at _MatchParser.dart._MatchParser.parseMatch$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:40464:20)
    at FindReferencesView.dart.FindReferencesView._references$_render$2 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:40333:36)
    at [object Object].<anonymous> (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24887:32)
    at ListTreeBuilder.dart.ListTreeBuilder.render$2 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:42615:28)
    at ListTreeBuilder.dart.ListTreeBuilder._addNode$2 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:42559:16)
    at ListTreeBuilder.dart.ListTreeBuilder._addNode$2 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:42581:18)
    at FindReferencesView__handleSearchResults_closure.dart.FindReferencesView__handleSearchResults_closure.call$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:40434:14)
    at _RootZone.dart._RootZone.runUnary$2 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:46503:20)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:44936:47)
    at [object Object].dart._Future.static._Future__propagateToListeners (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:44844:120)
    at _Future.dart._Future._complete$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:44696:13)
    at Stream_toList_closure0.dart.Stream_toList_closure0.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:45323:21)
    at _RootZone.dart._RootZone.runGuarded$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:46440:20)
    at _BufferingStreamSubscription__sendDone_sendDone.dart._BufferingStreamSubscription__sendDone_sendDone.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:45866:18)
    at _ControllerSubscription.dart._BufferingStreamSubscription._sendDone$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:45775:14)
    at _DelayedDone.dart._DelayedDone.perform$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:45903:18)
    at _PendingEvents_schedule_closure.dart._PendingEvents_schedule_closure.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:45944:16)
    at [object Object].dart._microtaskLoop (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:43837:27)
    at [object Object].dart._startMicrotaskLoop (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:43843:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23948:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:25836:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23560:25)
    at [object Object].dart._callInIsolate (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23202:28)
    at dart.invokeClosure (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24781:20)
    at /usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24802:18
```

### Commands

```
     -1:06.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:06.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:06.0 core:copy (atom-text-editor.editor.is-focused)
     -0:49.5.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:49.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:46.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.4.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:35 core:delete (atom-text-editor.editor.is-focused)
     -0:34.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:34.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:33.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:22.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-one-dark-ui)
     -0:00.8.0 dartlang:find-references (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "followSymlinks": false,
    "ignoredNames": [
      ".*"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "dartlang": {
    "formatOnSave": true,
    "sdkLocation": "/media/jimbe/mojossd/sysui/src/third_party/dart-sdk/dart-sdk",
    "showTodos": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.5
dartlang, v0.6.2
flutter, v0.2.1
last-cursor-position, v0.9.0
linter, v1.11.3
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
> (I have no idea what I did to cause this.)

The stack trace caught enough of the issue.
