### ISSUE TITLE
Uncaught 105: Extension errorIsolate must be runnable before this request is made.

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#808]
[Enter steps to reproduce below:]

1. Cmd-R to run a Flutter app. This is the second time I ran my app, after updating to the latest Flutter master branch.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.2

### Stack Trace

Uncaught 105: Extension error
Isolate must be runnable before this request is made.

```
At /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23569

105: Extension error
Isolate must be runnable before this request is made.
    at [object Object].dart.wrapException (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:24633:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:46425:19)
    at [object Object].dart._microtaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:43837:27)
    at [object Object].dart._startMicrotaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:43843:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23948:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:25836:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23560:25)
    at [object Object].dart._callInIsolate (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:23202:28)
    at dart.invokeClosure (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:24781:20)
    at /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:24802:18
```

### Commands

```
  2x -1:04.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:01.8.0 dartlang:run-application (atom-text-editor.editor.is-focused)
     -0:25.2.0 tree-view:copy (pre.console-line.tab-scrollable)
     -0:09.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.6.0 dartlang:run-application (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dart-tools",
      "minimap"
    ]
  },
  "dartlang": {
    "formatOnSave": true,
    "sdkLocation": "/Users/sethladd/homebrew/opt/dart/libexec",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.5
dartlang, v0.6.2
flutter, v0.2.1
highlight-selected, v0.11.2
last-cursor-position, v0.9.0
linter, v1.11.3
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by sethladd** [comment]
Third time I ran via Cmd-R, I saw this error. So, reproducing on my app here.

**Comment by devoncarew** [comment]
Fixed w/ a PR into the flutter repo -
