### ISSUE TITLE
Error popup when saving Sky dart files

### ISSUE THREAD

**Issue by iansf** [dart-atom/dartlang#82]
I just installed linter and dartlang using apm.  Now, every time I save a dart file my checkout of SkyEngine, I get the following error popup:

NoSuchMethodError: method not found: 'call' Receiver: Closure '_lint$1' of Instance of '_DartLinterProvider' Arguments: [Instance of 'JsObject', Instance of 'JsObject']

NoSuchMethodError: method not found: 'call'
Receiver: Closure '_lint$1' of Instance of '_DartLinterProvider'
Arguments: [Instance of 'JsObject', Instance of 'JsObject']
  at [object Object].dart.wrapException (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:9842:17)
  at [object Object].dart.Object.noSuchMethod$1 (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:19466:17)
  at [object Object].J.noSuchMethod$1 (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:22319:39)
  at [object Object].dart.Primitives_functionNoSuchMethod (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:9776:16)
  at [object Object].dart.Primitives__genericApplyFunctionWithPositionalArguments (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:9808:20)
  at [object Object].dart.Primitives_applyFunctionWithPositionalArguments (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:9794:16)
  at dart._callDartFunction (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:20930:31)
  at Object.lint (/Users/iansf/dev/atom-dartlang-experimental/web/entry.dart.js:21159:20)
  at /Users/iansf/.atom/packages/linter/lib/editor-linter.coffee:69:26
  at currentLinter (/Users/iansf/.atom/packages/linter/lib/editor-linter.coffee:68:20)
  at /Users/iansf/.atom/packages/linter/lib/editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/iansf/.atom/packages/linter/lib/editor-linter.coffee:64:26)
  at /Users/iansf/.atom/packages/linter/lib/editor-linter.coffee:57:27

**Comment by devoncarew** [comment]
> I just installed linter and dartlang using apm

If you do that, you'd probably need to run `npm install` in both directories in order to have their node deps satisfied. You might want to `apm unlink` them, and then re-install via the atom UI. That'll eliminate any potential install issues.

**Comment by iansf** [comment]
I think it may have been due to cruft from my previous install of dart-lang-experimental.  Removing that (and reinstalling dartlang and linter just in case) fixed the issue for me.  Thanks!

**Comment by devoncarew** [comment]
> fixed the issue for me

cool, good to hear
