### ISSUE TITLE
Uncaught 105: Extension errorIsolate must be runnable before this request is made.

### ISSUE THREAD

**Issue by jimbeveridge** [dart-atom/dartlang#833]
[Enter steps to reproduce below:]

I just clicked Run. I don't remember doing anything strange.

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.1
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.4

### Stack Trace

Uncaught 105: Extension error
Isolate must be runnable before this request is made.

```
At /usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23569

105: Extension error
Isolate must be runnable before this request is made.
    at [object Object].dart.wrapException (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24633:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:46425:19)
    at [object Object].dart._microtaskLoop (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:43837:27)
    at [object Object].dart._startMicrotaskLoop (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:43843:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23948:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:25836:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23560:25)
    at [object Object].dart._callInIsolate (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:23202:28)
    at dart.invokeClosure (/usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24781:20)
    at /usr/local/google/home/jimbe/.atom/packages/dartlang/web/entry.dart.js:24802:18
```

### Commands

```
     -0:00.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "followSymlinks": false,
    "ignoredNames": [
      ".*"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "dartlang": {
    "formatOnSave": true,
    "logging": "finer",
    "sdkLocation": "/media/jimbe/mojossd/sysui/src/third_party/dart-sdk/dart-sdk",
    "showTodos": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.5
dartlang, v0.6.4
flutter, v0.2.1
last-cursor-position, v0.9.0
linter, v1.11.3
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Another user report:

> Run app from Atom, it works fine but when running the same app from command line using flutter run, it threw the following error

**Comment by dabhaid** [comment]
+1 from Atom UI, but only on the "alpha" branch of Flutter. The "hackathon" branch runs fine.

**Steps:
**Packages > Flutter > Create new Flutter project
run 'pub get' on pubspec.yaml
$> open -a Simulator
run new project code. 

**Trace**
> Extension error (105) from resume():
> Isolate must be runnable before this request is made.
>     at [object Object].dart.wrapException (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:24616:17)
>     at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:46386:19)
>     at [object Object].dart._microtaskLoop (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:43798:27)
>     at [object Object].dart._startMicrotaskLoop (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:43804:11)
>     at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:23931:23)
>     at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:25819:29)
>     at _IsolateContext.dart._IsolateContext.eval$1 (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:23543:25)
>     at [object Object].dart._callInIsolate (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:23185:28)
>     at dart.invokeClosure (/Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:24764:20)
>     at /Users/djmurphy/.atom/packages/dartlang/web/entry.dart.js:24785:18
> 

**Installed Packages
> /Users/djmurphy/.atom/packages (6)
> ├── atom-toolbar@0.1.6
> ├── dartlang@0.6.4
> ├── emacs-plus@0.9.12
> ├── flutter@0.2.1
> ├── linter@1.11.3
> └── synced-sidebar@0.4.3
