### ISSUE TITLE
Uncaught TypeError: Cannot read property '_analysis' of null

### ISSUE THREAD

**Issue by rayk** [dart-atom/dartlang#865]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.5

### Stack Trace

Uncaught TypeError: Cannot read property '_analysis' of null

```
At /Users/rayk/.atom/packages/dartlang/web/entry.dart.js:24021

TypeError: Cannot read property '_analysis' of null
    at AnalysisServer.dart.AnalysisServer.getHover$2 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:27522:28)
    at TooltipManager__install_closure.dart.TooltipManager__install_closure.call$1 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:66571:78)
    at invokeClosure_closure0.dart.invokeClosure_closure0.call$0 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:26271:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:24012:25)
    at [object Object].dart._callInIsolate (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:23654:28)
    at dart.invokeClosure (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:25235:20)
    at ShadowRoot.<anonymous> (/Users/rayk/.atom/packages/dartlang/web/entry.dart.js:25254:18)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-csharp",
      "language-go",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-todo",
      "welcome"
    ],
    "followSymlinks": false,
    "projectHome": "/Users/rayk/Projects/",
    "themes": [
      "atom-material-ui",
      "slime"
    ]
  },
  "dartlang": {
    "debugAnalysisServer": true,
    "formatOnSave": true,
    "hoverTooltip": true,
    "sdkLocation": "/Users/rayk/Projects/flutter/bin/cache/dart-sdk",
    "showInfos": false,
    "showOutlineView": false,
    "showTodos": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-material-ui, v1.2.6
atom-toolbar, v0.1.6
atom-watcher, v1.1.5
color-picker, v2.1.1
dartlang, v0.6.5
epoch-converter, v0.1.0
file-icons, v1.6.18
flutter, v0.2.1
imdone-atom, v1.3.27
imdone-atom-github, v0.1.9
language-plantuml, v0.2.0
linter, v1.11.3
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
plantuml-viewer, v0.7.0
scroll-percentage, v1.2.1
slime, v1.6.1
synced-sidebar, v0.4.3
terminal-panel, v1.14.1
text-manipulation, v0.6.0
tool-bar, v0.3.0
tool-bar-almighty, v0.6.1
tool-bar-main, v0.0.9
tree-view-git-status, v0.2.3
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Thanks for the report. Seems related to the new `hoverTooltip` feature.

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/commit/455e3990b78642913a3a11791594913ce1139f43
