### ISSUE TITLE
Uncaught NullError: method not found: 'apply' on null

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#892]
[Enter steps to reproduce below:]

1. Cmd-Shift-P
1. type "find type"
1. Enter `StatefulWidget`

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.7

### Stack Trace

Uncaught NullError: method not found: 'apply' on null

```
At /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:26802

TypeError: Cannot read property 'apply' of undefined
    at JsObject.dart.JsObject.callMethod$2 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:61224:43)
    at JsObject.dart.JsObject.callMethod$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:61227:21)
    at TextEditor.dart.ProxyHolder.invoke$4 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:64819:23)
    at TextEditor.dart.ProxyHolder.invoke$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:64826:21)
    at FindTypeHelper__handleFindType_closure.dart.FindTypeHelper__handleFindType_closure.call$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:63477:52)
    at _RootZone.dart._RootZone.runUnary$2 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:49821:20)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:48164:47)
    at [object Object].dart._Future.static._Future__propagateToListeners (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:48072:120)
    at _Future.dart._Future._completeWithValue$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:47931:11)
    at _Future__asyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:48149:20)
    at [object Object].dart._microtaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:46986:27)
    at [object Object].dart._startMicrotaskLoop (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:46992:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:27182:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:29047:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:26793:25)
    at [object Object].dart._callInIsolate (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:26435:28)
    at dart.invokeClosure (/Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:28015:20)
    at /Users/sethladd/.atom/packages/dartlang/web/entry.dart.js:28036:18
```

### Commands

```
  5x -7:40.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:37.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:31.5.0 dartlang:send-feedback (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:45.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:08.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 dartlang:find-type (atom-text-editor.editor)
     -0:02.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dart-tools",
      "minimap"
    ]
  },
  "dartlang": {
    "formatOnSave": true,
    "sdkLocation": "/Users/sethladd/Code/flutter/bin/cache/dart-sdk",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.7
flutter, v0.2.1
highlight-selected, v0.11.2
last-cursor-position, v0.9.0
linter, v1.11.4
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
This will happen when there are no editor's currently open (will add a fix).

**Comment by pulyaevskiy** [comment]
"Find type" does not work for me at all, always throwing the above exception with or without open files in editor. Atom 1.6.0, Dart plugin 0.6.7, OSX 10.11.3.

I tried to restart Atom after update a couple times.

**Comment by sethladd** [comment]
Hm, I'm pretty sure I had an editor open for lib/main.dart

**Comment by franklinyu** [comment]
I got a similar error: the message is the same, but I don't know how to get the stack trace. Any help?
