### ISSUE TITLE
Uncaught NullError: method not found: 'matchAsPrefix$2' on null

### ISSUE THREAD

**Issue by mezoni** [dart-atom/dartlang#969]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 16.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.13

### Stack Trace

Uncaught NullError: method not found: 'matchAsPrefix$2' on null

```
At /home/andrew/.atom/packages/dartlang/web/entry.dart.js:26807

TypeError: Cannot read property 'matchAsPrefix$2' of null
    at [object Object].J.matchAsPrefix$2$s (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:75766:40)
    at JSString.dart.JSString.startsWith$2 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:26156:18)
    at JSString.dart.JSString.startsWith$1 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:26159:21)
    at [object Object].J.startsWith$1$s (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:75853:41)
    at UriResolver__resolvePathToUris_closure0.dart.UriResolver__resolvePathToUris_closure0.call$1 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:34042:15)
    at _RootZone.dart._RootZone.runUnary$2 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:49135:20)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:47478:47)
    at [object Object].dart._Future.static._Future__propagateToListeners (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:47386:120)
    at _Future.dart._Future._completeWithValue$1 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:47245:11)
    at _Future__asyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:47463:20)
    at [object Object].dart._microtaskLoop (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:46300:27)
    at [object Object].dart._startMicrotaskLoop (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:46306:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:27187:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:29051:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:26798:25)
    at [object Object].dart._callInIsolate (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:26440:28)
    at dart.invokeClosure (/home/andrew/.atom/packages/dartlang/web/entry.dart.js:28020:20)
    at /home/andrew/.atom/packages/dartlang/web/entry.dart.js:28041:18
```

### Commands

```
     -5:15.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:11 tree-view:add-folder (div.header.list-item)
     -5:04.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:57 tree-view:add-file (span.name.icon.icon-file-directory)
     -4:47 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:46.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:45.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -4:42.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:14.2.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -4:13.6.0 core:delete (atom-text-editor.editor.is-focused)
  2x -4:08.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:07.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:56.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:14.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "/home/andrew/tool/dart/dart-sdk"
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.13
linter, v1.11.4
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by devoncarew** [comment]
Fixed! Thanks for the report.
